import React,{useEffect,useState}from'react';
import{Alert,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View}from'react-native';
import{supabase}from'../lib/supabase';
import{cancelAccountDeletion,getPreferences,requestAccountDeletion}from'../lib/api';
import{C,F,R,S}from'../lib/theme';

export default function AccountScreen({navigation}:any){
 const[confirm,setConfirm]=useState('');const[reason,setReason]=useState('');const[busy,setBusy]=useState(false);const[pending,setPending]=useState(false);const[checking,setChecking]=useState(true);
 useEffect(()=>{let alive=true;getPreferences().then((x:any)=>{if(alive)setPending(!!x?.deactivated_at)}).catch(()=>{}).finally(()=>alive&&setChecking(false));return()=>{alive=false}},[]);
 const request=async()=>{if(confirm.trim().toUpperCase()!=='DELETE')return Alert.alert('Confirmation required','Type DELETE to request account deletion.');setBusy(true);try{await requestAccountDeletion(reason.trim()||undefined);setPending(true);Alert.alert('Deletion requested','Your public profile is now deactivated. You can sign back in and cancel while the request is still pending.',[{text:'OK',onPress:()=>void supabase.auth.signOut()}])}catch{Alert.alert('Could not request deletion','Please try again.')}finally{setBusy(false)}};
 const cancel=async()=>{setBusy(true);try{await cancelAccountDeletion();setPending(false);setConfirm('');Alert.alert('Request cancelled','Your public profile has been reactivated.')}catch{Alert.alert('Could not cancel','Please try again.')}finally{setBusy(false)}};
 return<ScrollView style={s.page} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.head}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={s.back}>‹ Settings</Text></TouchableOpacity><Text style={s.wordmark}>WORK<Text style={{color:C.violet2}}>IT</Text></Text></View><Text style={s.kicker}>ACCOUNT</Text><Text style={s.h1}>Your account. Your control.</Text><View style={s.card}><Text style={s.cardT}>Sign out</Text><Text style={s.cardB}>End this session on the current device.</Text><TouchableOpacity onPress={()=>supabase.auth.signOut()} style={s.secondary}><Text style={s.secondaryTxt}>Log out</Text></TouchableOpacity></View><View style={[s.card,s.danger]}><Text style={s.dangerK}>DANGER ZONE</Text><Text style={s.cardT}>Delete WORKIT account</Text><Text style={s.cardB}>This starts an account deletion request and immediately hides your public profile. Some records may be retained where required for safety, fraud prevention, accounting or legal obligations.</Text>{pending&&!checking?<View style={s.pending}><Text style={s.pendingT}>DELETION PENDING</Text><Text style={s.pendingB}>Your public profile is currently deactivated.</Text></View>:null}{!pending&&<><TextInput value={reason} onChangeText={setReason} placeholder="Reason (optional)" placeholderTextColor={C.faint} style={s.input}/><Text style={s.confirmLabel}>Type DELETE to confirm</Text><TextInput value={confirm} onChangeText={setConfirm} autoCapitalize="characters" placeholder="DELETE" placeholderTextColor={C.faint} style={s.input}/></>}{checking?<Text style={s.checking}>Checking account status…</Text>:pending?<TouchableOpacity disabled={busy} onPress={cancel} style={s.cancel}><Text style={s.cancelTxt}>{busy?'Cancelling…':'Cancel deletion request'}</Text></TouchableOpacity>:<TouchableOpacity disabled={busy} onPress={request} style={s.delete}><Text style={s.deleteTxt}>{busy?'Submitting…':'Request account deletion'}</Text></TouchableOpacity>}</View></ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingTop:S.top,paddingHorizontal:S.pageX,paddingBottom:90},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},back:{color:C.violetSoft,fontSize:12,fontWeight:'800'},wordmark:{color:C.text,fontFamily:F.display,fontSize:27,fontWeight:'700'},kicker:{color:C.violetSoft,fontSize:9,fontWeight:'900',letterSpacing:1.3,marginTop:26},h1:{color:C.text,fontSize:30,fontWeight:'900',letterSpacing:-1,marginTop:6,marginBottom:10},card:{marginTop:12,borderWidth:1,borderColor:C.lineSoft,borderRadius:R.lg,backgroundColor:C.panel,padding:16},danger:{borderColor:'#4B2028'},dangerK:{color:C.red,fontSize:8,fontWeight:'900',letterSpacing:1.2,marginBottom:7},cardT:{color:C.text,fontSize:16,fontWeight:'900'},cardB:{color:C.muted,fontSize:10,lineHeight:16,marginTop:6},secondary:{alignSelf:'flex-start',marginTop:14,borderWidth:1,borderColor:C.line,borderRadius:12,paddingHorizontal:14,paddingVertical:10},secondaryTxt:{color:C.text,fontSize:9,fontWeight:'900'},confirmLabel:{color:C.muted,fontSize:9,fontWeight:'800',marginTop:15,marginBottom:6},input:{borderWidth:1,borderColor:C.line,borderRadius:13,backgroundColor:C.panel2,paddingHorizontal:12,paddingVertical:12,color:C.text,fontSize:11,marginTop:10},pending:{marginTop:14,borderRadius:13,borderWidth:1,borderColor:'#6A3038',backgroundColor:'#211116',padding:12},pendingT:{color:C.red,fontSize:8,fontWeight:'900',letterSpacing:1},pendingB:{color:C.muted,fontSize:9,marginTop:5},checking:{color:C.faint,fontSize:9,marginTop:14},delete:{marginTop:14,height:48,borderRadius:13,backgroundColor:C.red,alignItems:'center',justifyContent:'center'},deleteTxt:{color:'#fff',fontSize:10,fontWeight:'900'},cancel:{marginTop:14,height:48,borderRadius:13,borderWidth:1,borderColor:C.green,alignItems:'center',justifyContent:'center'},cancelTxt:{color:C.green,fontSize:10,fontWeight:'900'}});
