import React,{useEffect,useState}from'react';
import{View,Text,ScrollView,TouchableOpacity,StyleSheet,Alert}from'react-native';
import{getMyJobs,openConversation,sendMessage}from'../lib/api';
import{createCandidateInvite,markCandidateInviteDelivered}from'../lib/hiringInvites';
import{C,R,S}from'../lib/theme';

export default function CandidateInviteScreen({route,navigation}:any){
 const candidate=route.params?.candidate;const[jobs,setJobs]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[sending,setSending]=useState<string|null>(null);
 useEffect(()=>{getMyJobs().then(r=>setJobs(r.items||[])).catch(()=>setJobs([])).finally(()=>setLoading(false))},[]);
 const invite=async(job:any)=>{if(!candidate?.id||sending)return;setSending(job.id);try{const c=await openConversation(candidate.id);const record=await createCandidateInvite({candidate_id:candidate.id,job_post_id:job.id,conversation_id:c.id});if(!record.should_send){Alert.alert('Already invited','You already invited this person to this role. Opening your conversation instead.');navigation.replace('Chat',{conversationId:c.id,other:candidate});return}const title=job.title||'a role';const jd=job.job||{};const company=jd.organization?.name||jd.company_name||'our team';await sendMessage(c.id,`[WORKIT_JOB:${job.id}] WORKIT JOB INVITE\n\nI'd like to invite you to apply for “${title}” at ${company}. Your WORKIT profile and work caught my attention.`);try{await markCandidateInviteDelivered(record.id)}catch{try{await markCandidateInviteDelivered(record.id)}catch{}}navigation.replace('Chat',{conversationId:c.id,other:candidate})}catch(e:any){Alert.alert('Could not send invite',e?.message||'Please try again.')}finally{setSending(null)}};
 return<ScrollView style={s.page} contentContainerStyle={s.content}>
  <View style={s.top}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={s.back}>‹</Text></TouchableOpacity><View style={{alignItems:'center'}}><Text style={s.kicker}>INVITE TO APPLY</Text><Text style={s.title}>Choose a job</Text></View><View style={{width:32}}/></View>
  <Text style={s.intro}>Invite <Text style={s.strong}>{candidate?.full_name||'this professional'}</Text> to one of your open roles. They’ll get a clickable job card directly in WORKIT Messages.</Text>
  {loading?<Text style={s.empty}>Loading your jobs…</Text>:jobs.length===0?<View style={s.emptyCard}><Text style={s.emptyTitle}>No open jobs yet</Text><Text style={s.empty}>Post a job first, then return to this profile to invite the person directly.</Text><TouchableOpacity onPress={()=>navigation.navigate('MainTabs',{screen:'Post'})} style={s.primary}><Text style={s.primaryTxt}>Post a job</Text></TouchableOpacity></View>:jobs.map((j:any)=>{const jd=j.job||{};const org=jd.organization||{};return<TouchableOpacity key={j.id} onPress={()=>void invite(j)} disabled={!!sending} style={s.job} activeOpacity={.85}><View style={{flex:1}}><Text style={s.jobTitle}>{j.title||'Open role'}</Text><Text style={s.meta}>{org.name||jd.company_name||'WORKIT employer'} · {String(jd.workplace_type||(jd.is_remote?'remote':'on_site')).replace('_',' ')}{jd.location?` · ${jd.location}`:''}</Text></View><View style={s.invite}><Text style={s.inviteTxt}>{sending===j.id?'Sending…':'Invite'}</Text></View></TouchableOpacity>})}
 </ScrollView>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingTop:S.top,paddingHorizontal:S.pageX,paddingBottom:100},top:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{color:C.text,fontSize:36,lineHeight:40},kicker:{color:C.violetSoft,fontSize:8,fontWeight:'900',letterSpacing:1.4},title:{color:C.text,fontSize:24,fontWeight:'900',marginTop:3},intro:{color:C.muted,fontSize:12,lineHeight:19,marginTop:22,marginBottom:18},strong:{color:C.text,fontWeight:'900'},job:{minHeight:86,borderRadius:18,borderWidth:1,borderColor:C.lineSoft,backgroundColor:C.panel,padding:14,marginBottom:9,flexDirection:'row',alignItems:'center',gap:10},jobTitle:{color:C.text,fontSize:14,fontWeight:'900'},meta:{color:C.muted,fontSize:9,marginTop:5,textTransform:'capitalize'},invite:{height:40,paddingHorizontal:15,borderRadius:12,backgroundColor:C.text,alignItems:'center',justifyContent:'center'},inviteTxt:{color:C.black,fontSize:9,fontWeight:'900'},emptyCard:{padding:20,borderRadius:18,borderWidth:1,borderColor:C.lineSoft,backgroundColor:C.panel},emptyTitle:{color:C.text,fontSize:17,fontWeight:'900'},empty:{color:C.muted,fontSize:11,lineHeight:18,marginTop:8},primary:{height:46,borderRadius:13,backgroundColor:C.text,alignItems:'center',justifyContent:'center',marginTop:16},primaryTxt:{color:C.black,fontSize:10,fontWeight:'900'}});