import React,{useEffect,useState}from'react';
import{Alert,ScrollView,StyleSheet,Switch,Text,TextInput,TouchableOpacity,View}from'react-native';
import{getMe,updateMe}from'../lib/api';
import{C,F,R,S}from'../lib/theme';

const arr=(v:string)=>v.split(',').map((x:string)=>x.trim()).filter(Boolean);
const rows=(v:string,kind:'q'|'c')=>v.split('\n').map((x:string)=>x.trim()).filter(Boolean).map((line:string)=>{const p=line.split('|').map((x:string)=>x.trim());return kind==='q'?{degree:p[0]||'',institution:p[1]||'',years:p[2]||''}:{name:p[0]||'',issuer:p[1]||''}});

export default function EditProfileScreen({navigation}:any){
 const[p,setP]=useState<any>(null);const[busy,setBusy]=useState(false);
 const[field,setField]=useState<any>({full_name:'',title:'',bio:'',location:'',skills:'',tools:'',languages:'',qualifications:'',certifications:'',available_for_work:true,hourly_rate:''});
 useEffect(()=>{getMe().then((x:any)=>{setP(x);setField({full_name:x.full_name||'',title:x.title||'',bio:x.bio||'',location:x.location||'',skills:(x.skills||[]).join(', '),tools:(x.tools||[]).join(', '),languages:(x.languages||[]).join(', '),qualifications:(x.qualifications||[]).map((q:any)=>[q.degree||q.title,q.institution||q.school,q.years].filter(Boolean).join(' | ')).join('\n'),certifications:(x.certifications||[]).map((c:any)=>[c.name||c.title,c.issuer].filter(Boolean).join(' | ')).join('\n'),available_for_work:!!x.available_for_work,hourly_rate:x.hourly_rate?String(x.hourly_rate):''})})},[]);
 const set=(k:string,v:any)=>setField((f:any)=>({...f,[k]:v}));
 const completed=[field.full_name,field.title,field.bio,field.location,field.skills,field.tools,field.languages,field.qualifications,field.certifications,field.hourly_rate].filter((v:any)=>String(v||'').trim()).length;
 const score=Math.round(completed/10*100);
 const save=async()=>{setBusy(true);try{await updateMe({full_name:field.full_name.trim(),title:field.title.trim(),bio:field.bio.trim(),location:field.location.trim(),skills:arr(field.skills),tools:arr(field.tools),languages:arr(field.languages),qualifications:rows(field.qualifications,'q'),certifications:rows(field.certifications,'c'),available_for_work:field.available_for_work,hourly_rate:field.hourly_rate?Number(field.hourly_rate):null});Alert.alert('Profile updated','Your professional identity is live on WORKIT.');navigation.goBack()}catch{Alert.alert('Could not save','Please try again.')}finally{setBusy(false)}};
 if(!p)return<View style={s.page}/>;
 return<ScrollView style={s.page} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
  <View style={s.head}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={s.back}>‹ Back</Text></TouchableOpacity><Text style={s.wordmark}>WORK<Text style={{color:C.violet2}}>IT</Text></Text></View>
  <Text style={s.kicker}>PROFESSIONAL IDENTITY</Text><Text style={s.h1}>Make your profile prove what you can do.</Text><Text style={s.sub}>Qualifications, tools and skills are searchable and visible to employers and clients.</Text>
  <View style={s.scoreCard}><View><Text style={s.scoreK}>PROFILE STRENGTH</Text><Text style={s.scoreN}>{score}%</Text><Text style={s.scoreB}>{score>=80?'Strong profile — ready to be discovered.':score>=50?'Good start — add more proof signals.':'Complete your profile to improve discovery.'}</Text></View><View style={s.ring}><Text style={s.ringTxt}>{score}</Text></View></View>
  <Section t="Identity"><Input l="Full name" v={field.full_name} on={(x:string)=>set('full_name',x)}/><Input l="Profession / title" v={field.title} on={(x:string)=>set('title',x)} ph="Architect, Welder, Nurse, Developer..."/><Input l="Location" v={field.location} on={(x:string)=>set('location',x)} ph="Valletta, Malta"/><Input l="Bio" v={field.bio} on={(x:string)=>set('bio',x)} area/></Section>
  <Section t="Skills & software"><Input l="Skills" v={field.skills} on={(x:string)=>set('skills',x)} ph="Interior Design, 3D Visualization, Client Communication"/><Input l="Tools & software" v={field.tools} on={(x:string)=>set('tools',x)} ph="AutoCAD, Revit, Figma, Excel"/><Input l="Languages" v={field.languages} on={(x:string)=>set('languages',x)} ph="English, Albanian, Italian"/></Section>
  <Section t="Credentials"><Text style={s.help}>One qualification per line: Degree | Institution | Years</Text><Input l="Qualifications" v={field.qualifications} on={(x:string)=>set('qualifications',x)} area ph={'B.Arch | University of Malta | 2018–2023'}/><Text style={s.help}>One certification per line: Certification | Issuer</Text><Input l="Certifications" v={field.certifications} on={(x:string)=>set('certifications',x)} area ph={'Autodesk Certified Professional | Autodesk'}/></Section>
  <Section t="Work status"><View style={s.toggle}><View><Text style={s.toggleT}>Available for work</Text><Text style={s.toggleB}>Appear in employer search as available.</Text></View><Switch value={field.available_for_work} onValueChange={(x:boolean)=>set('available_for_work',x)} trackColor={{true:C.violet}}/></View><Input l="Hourly rate (€)" v={field.hourly_rate} on={(x:string)=>set('hourly_rate',x)} ph="45" keyboard="decimal-pad"/></Section>
  <TouchableOpacity disabled={busy} onPress={save} style={[s.save,{opacity:busy?.6:1}]}><Text style={s.saveTxt}>{busy?'Saving…':'Save professional identity'}</Text><Text style={s.saveTxt}>→</Text></TouchableOpacity>
 </ScrollView>}
const Section=({t,children}:any)=><View style={s.section}><Text style={s.sectionT}>{t}</Text>{children}</View>;
const Input=({l,v,on,ph,area,keyboard}:any)=><View style={{marginTop:12}}><Text style={s.label}>{l}</Text><TextInput value={v} onChangeText={on} placeholder={ph} placeholderTextColor={C.faint} keyboardType={keyboard||'default'} multiline={!!area} style={[s.input,area&&s.area]}/></View>;
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingTop:S.top,paddingHorizontal:S.pageX,paddingBottom:90},head:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{color:C.violetSoft,fontSize:12,fontWeight:'800'},wordmark:{color:C.text,fontFamily:F.display,fontSize:27,fontWeight:'700'},kicker:{color:C.violetSoft,fontSize:9,fontWeight:'900',letterSpacing:1.4,marginTop:24},h1:{color:C.text,fontSize:29,fontWeight:'900',lineHeight:34,letterSpacing:-1,marginTop:6},sub:{color:C.muted,fontSize:12,lineHeight:19,marginTop:7},scoreCard:{marginTop:16,borderWidth:1,borderColor:'#332A63',borderRadius:R.lg,backgroundColor:'#151229',padding:15,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},scoreK:{color:C.violetSoft,fontSize:8,fontWeight:'900',letterSpacing:1.1},scoreN:{color:C.text,fontSize:24,fontWeight:'900',marginTop:4},scoreB:{color:C.muted,fontSize:9,marginTop:4,maxWidth:240},ring:{width:52,height:52,borderRadius:26,borderWidth:4,borderColor:C.violet,alignItems:'center',justifyContent:'center'},ringTxt:{color:C.text,fontSize:12,fontWeight:'900'},section:{marginTop:16,borderWidth:1,borderColor:C.lineSoft,borderRadius:R.lg,backgroundColor:C.panel,padding:14},sectionT:{color:C.text,fontSize:15,fontWeight:'900'},label:{color:C.muted,fontSize:9,fontWeight:'800',marginBottom:6},input:{borderWidth:1,borderColor:C.line,borderRadius:14,backgroundColor:C.panel2,paddingHorizontal:12,paddingVertical:12,color:C.text,fontSize:12},area:{minHeight:92,textAlignVertical:'top'},help:{color:C.faint,fontSize:8,lineHeight:13,marginTop:11},toggle:{minHeight:62,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderWidth:1,borderColor:C.line,borderRadius:14,backgroundColor:C.panel2,paddingHorizontal:12,marginTop:12},toggleT:{color:C.text,fontSize:11,fontWeight:'900'},toggleB:{color:C.faint,fontSize:8,marginTop:3},save:{height:56,borderRadius:17,backgroundColor:C.violet,marginTop:18,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},saveTxt:{color:'#fff',fontSize:12,fontWeight:'900'}});