import React,{useEffect,useState}from'react';
import{View,Text,TextInput,TouchableOpacity,StyleSheet,ScrollView}from'react-native';
import{getFeed,getJobs,getMarket,searchTalent}from'../lib/api';
import{C,F,S}from'../lib/theme';

export default function GlobalSearchScreen({navigation,route}:any){
 const[q,setQ]=useState(route?.params?.skill||'');const[loading,setLoading]=useState(false);const[people,setPeople]=useState<any[]>([]);const[work,setWork]=useState<any[]>([]);const[jobs,setJobs]=useState<any[]>([]);const[market,setMarket]=useState<any[]>([]);
 useEffect(()=>{const t=setTimeout(()=>{void run()},220);return()=>clearTimeout(t)},[q]);
 const run=async()=>{setLoading(true);try{const[p,w,j,m]=await Promise.all([searchTalent({query:q,limit:10}),getFeed(undefined,'for_you'),getJobs({limit:30}),getMarket({q})]);const needle=q.trim().toLowerCase();setPeople(p.items||[]);setWork((w.items||[]).filter((x:any)=>!needle||`${x.title||''} ${x.description||''} ${x.author?.full_name||''} ${x.author?.title||''} ${(x.tags||[]).join(' ')}`.toLowerCase().includes(needle)).slice(0,8));setJobs((j.items||[]).filter((x:any)=>{const jd=x.job||{};return!needle||`${x.title||''} ${x.description||''} ${jd.company_name||''} ${jd.location||''} ${(x.tags||[]).join(' ')}`.toLowerCase().includes(needle)}).slice(0,10));setMarket(m.items||[])}catch{}finally{setLoading(false)}};
 const openPerson=(p:any)=>navigation.navigate('Professional',{username:p.username,profile:p});
 return<ScrollView style={s.page} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
  <View style={s.head}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={s.back}>‹</Text></TouchableOpacity><Text style={s.title}>Search WORKIT</Text></View>
  <View style={s.search}><Text style={s.searchIcon}>⌕</Text><TextInput autoFocus value={q} onChangeText={setQ} placeholder="People, professions, work, jobs..." placeholderTextColor={C.faint} style={s.input}/></View>
  {loading&&<Text style={s.loading}>Searching WORKIT…</Text>}
  <Section t="People"><View style={s.stack}>{people.map((p:any)=><TouchableOpacity key={p.id} onPress={()=>openPerson(p)} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{p.full_name} {p.verified?'✓':''}</Text><Text style={s.rowSub}>{p.title||'Professional'} · {p.location||'Global'}</Text><Text numberOfLines={1} style={s.tags}>{[...(p.tools||[]),...(p.skills||[])].slice(0,4).join(' · ')}</Text></View><Text style={s.arrow}>›</Text></TouchableOpacity>)}</View></Section>
  <Section t="Work"><View style={s.stack}>{work.map((x:any)=><TouchableOpacity key={x.id} onPress={()=>x.author&&openPerson(x.author)} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{x.title||'Work proof'}</Text><Text style={s.rowSub}>{x.author?.full_name||'WORKIT member'} · {x.author?.title||String(x.type||'work').replace('_',' ')}</Text></View><Text style={s.workIcon}>▶</Text></TouchableOpacity>)}</View></Section>
  <Section t="Jobs"><View style={s.stack}>{jobs.map((j:any)=>{const jd=j.job||{};const org=jd.organization||{};return<TouchableOpacity key={j.id} onPress={()=>navigation.navigate('JobDetail',{jobId:j.id})} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{j.title}</Text><Text style={s.rowSub}>{org.name||jd.company_name||'WORKIT employer'}{org.verified?' ✓':''} · {jd.workplace_type?String(jd.workplace_type).replace('_',' '):(jd.is_remote?'Remote':'On-site')}</Text><Text numberOfLines={1} style={s.tags}>{jd.location||org.location||j.country_code||''}</Text></View><Text style={s.arrow}>›</Text></TouchableOpacity>})}</View></Section>
  <Section t="Market"><View style={s.stack}>{market.map((m:any)=><TouchableOpacity key={m.id} onPress={()=>navigation.navigate('MarketDetail',{id:m.id})} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{m.title}</Text><Text style={s.rowSub}>{m.type} · {m.currency||'EUR'} {m.price_amount||0}</Text></View><Text style={s.arrow}>›</Text></TouchableOpacity>)}</View></Section>
 </ScrollView>
}
const Section=({t,children}:any)=><View style={{marginTop:22}}><Text style={s.kicker}>{t.toUpperCase()}</Text>{children}</View>;
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingTop:S.top,paddingHorizontal:S.pageX,paddingBottom:80},head:{flexDirection:'row',alignItems:'center',gap:12},back:{color:C.text,fontSize:36,lineHeight:38},title:{color:C.text,fontFamily:F.display,fontSize:27},search:{height:56,marginTop:18,borderRadius:18,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,flexDirection:'row',alignItems:'center',paddingHorizontal:14},searchIcon:{color:C.text,fontSize:23,marginRight:8},input:{flex:1,color:C.text,fontSize:14},loading:{color:C.violetSoft,fontSize:9,fontWeight:'800',marginTop:9},kicker:{color:C.faint,fontSize:8,fontWeight:'900',letterSpacing:1.5,marginBottom:8},stack:{gap:8},row:{minHeight:72,borderRadius:15,borderWidth:1,borderColor:C.lineSoft,backgroundColor:C.panel,padding:13,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},rowTitle:{color:C.text,fontSize:13,fontWeight:'900'},rowSub:{color:C.muted,fontSize:9,marginTop:4,textTransform:'capitalize'},tags:{color:C.violetSoft,fontSize:8,marginTop:5,maxWidth:280},arrow:{color:C.text,fontSize:24},workIcon:{color:C.violetSoft,fontSize:17}});