import React,{useCallback,useMemo,useState}from'react';
import{Image,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View}from'react-native';
import{useFocusEffect}from'@react-navigation/native';
import{getConversations}from'../lib/api';
import{C,F,R,S}from'../lib/theme';

export default function InboxScreen({navigation}:any){
 const[items,setItems]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[query,setQuery]=useState('');const[filter,setFilter]=useState('All');
 const load=useCallback(async()=>{setLoading(true);try{const r:any=await getConversations();setItems(Array.isArray(r)?r:r.items||[])}catch{setItems([])}finally{setLoading(false)}},[]);
 useFocusEffect(useCallback(()=>{void load();return()=>{}},[load]));
 const visible=useMemo(()=>items.filter((c:any)=>{const q=query.trim().toLowerCase();const searchOk=!q||`${c.other?.full_name||''} ${c.last_message?.body||''} ${c.other?.title||''}`.toLowerCase().includes(q);const filterOk=filter==='All'||(filter==='Unread'&&c.unread>0)||(filter==='Hiring'&&c.context_type==='hiring')||(filter==='Orders'&&c.context_type==='order');return searchOk&&filterOk}),[items,query,filter]);
 const preview=(body?:string)=>String(body||'Start a work conversation').replace(/^\[WORKIT_(?:JOB|ORDER):[^\]]+\]\s*/,'').split('\n').filter(Boolean)[0]||'Work conversation';
 return<ScrollView style={s.page} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
  <View style={s.top}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={s.back}>‹</Text></TouchableOpacity><View><Text style={s.wordmark}>WORK<Text style={{color:C.violet2}}>IT</Text></Text><Text style={s.tagline}>WORK CONVERSATIONS</Text></View><TouchableOpacity onPress={()=>navigation.navigate('Notifications')}><Text style={s.bell}>♢</Text></TouchableOpacity></View>
  <Text style={s.h1}>Messages</Text><Text style={s.sub}>Hiring, work and opportunities — without email chains.</Text>
  <View style={s.search}><Text style={s.searchIcon}>⌕</Text><TextInput value={query} onChangeText={setQuery} placeholder="Search people or conversations..." placeholderTextColor={C.faint} style={s.searchInput}/></View>
  <View style={s.filters}>{['All','Hiring','Orders','Unread'].map(x=><TouchableOpacity key={x} onPress={()=>setFilter(x)} style={[s.filterBtn,filter===x&&s.filterOn]}><Text style={[s.filterTxt,filter===x&&s.filterTxtOn]}>{x}</Text>{x==='Unread'&&items.some((i:any)=>i.unread>0)?<View style={s.redDot}/>:null}</TouchableOpacity>)}</View>
  <View style={s.list}>{loading?<Text style={s.empty}>Loading conversations…</Text>:visible.length?visible.map((c:any)=><TouchableOpacity key={c.id} style={[s.row,c.unread>0&&s.rowUnread]} onPress={()=>navigation.navigate('Chat',{conversationId:c.id,other:c.other})} activeOpacity={.85}>{c.other?.avatar_url?<Image source={{uri:c.other.avatar_url}} style={s.avatar}/>:<View style={[s.avatar,s.ph]}><Text style={s.letter}>{c.other?.full_name?.[0]||'W'}</Text></View>}<View style={s.body}><View style={s.rowTop}><View style={{flex:1}}><Text numberOfLines={1} style={s.name}>{c.other?.full_name||'WORKIT member'} {c.other?.verified?'✓':''}</Text><Text numberOfLines={1} style={s.role}>{c.other?.title||labelContext(c.context_type)}</Text></View><Text style={s.time}>{formatTime(c.last_message?.created_at)}</Text></View><View style={s.previewRow}><Text numberOfLines={2} style={[s.preview,c.unread>0&&s.previewUnread]}>{preview(c.last_message?.body)}</Text>{c.unread>0?<View style={s.badge}><Text style={s.badgeTxt}>{c.unread}</Text></View>:<Text style={s.chev}>›</Text>}</View></View></TouchableOpacity>):<View style={s.emptyCard}><Text style={s.emptyTitle}>No conversations here.</Text><Text style={s.empty}>{filter==='All'?'When you hire, apply or message someone, the conversation will appear here.':`No ${filter.toLowerCase()} conversations right now.`}</Text></View>}</View>
 </ScrollView>
}
function labelContext(x?:string){if(x==='hiring')return'Hiring conversation';if(x==='order')return'Order conversation';return'WORKIT professional'}
function formatTime(v?:string){if(!v)return'';const d=new Date(v);const diff=Math.max(0,Date.now()-d.getTime());const m=Math.floor(diff/60000);if(m<60)return`${Math.max(1,m)} min ago`;const h=Math.floor(m/60);if(h<24)return`${h} hr ago`;return`${Math.floor(h/24)} d ago`}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingTop:S.top,paddingHorizontal:S.pageX,paddingBottom:80},top:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{color:C.text,fontSize:35,lineHeight:38},wordmark:{color:C.text,fontFamily:F.display,fontSize:28,fontWeight:'700',letterSpacing:-1.2},tagline:{color:C.muted,fontSize:6.5,fontWeight:'800',letterSpacing:1.7,marginTop:-1},bell:{color:C.text,fontSize:25},h1:{color:C.text,fontFamily:F.display,fontSize:34,marginTop:22},sub:{color:C.muted,fontSize:12,marginTop:3},search:{height:55,borderRadius:17,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,marginTop:14,flexDirection:'row',alignItems:'center',paddingHorizontal:14},searchIcon:{color:C.text,fontSize:22,marginRight:8},searchInput:{flex:1,color:C.text,fontSize:12},filters:{flexDirection:'row',gap:8,marginTop:14},filterBtn:{flex:1,height:43,borderRadius:14,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:5},filterOn:{backgroundColor:C.violet3,borderColor:C.violetSoft},filterTxt:{color:C.muted,fontSize:9,fontWeight:'800'},filterTxtOn:{color:C.white},redDot:{width:7,height:7,borderRadius:4,backgroundColor:C.red},list:{marginTop:17,gap:8},row:{minHeight:94,borderRadius:17,borderWidth:1,borderColor:C.lineSoft,backgroundColor:C.panel,padding:11,flexDirection:'row',alignItems:'center'},rowUnread:{borderColor:'rgba(139,92,246,.45)',backgroundColor:'rgba(139,92,246,.06)'},avatar:{width:59,height:59,borderRadius:30},ph:{backgroundColor:C.panel2,alignItems:'center',justifyContent:'center'},letter:{color:C.text,fontFamily:F.display,fontSize:21},body:{flex:1,marginLeft:11},rowTop:{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between'},name:{color:C.text,fontSize:13,fontWeight:'900'},role:{color:C.muted,fontSize:9,marginTop:2},time:{color:C.faint,fontSize:8,marginLeft:8},previewRow:{flexDirection:'row',alignItems:'center',marginTop:6},preview:{color:C.muted,fontSize:10,lineHeight:14,flex:1},previewUnread:{color:C.text,fontWeight:'700'},badge:{minWidth:24,height:24,borderRadius:12,backgroundColor:C.violet3,alignItems:'center',justifyContent:'center',paddingHorizontal:6},badgeTxt:{color:C.white,fontSize:9,fontWeight:'900'},chev:{color:C.faint,fontSize:22},emptyCard:{padding:22,borderRadius:18,borderWidth:1,borderColor:C.lineSoft,backgroundColor:C.panel},emptyTitle:{color:C.text,fontFamily:F.display,fontSize:21},empty:{color:C.muted,fontSize:10,lineHeight:16,marginTop:6}});