import React,{useEffect,useState}from'react';
import{View,Text,ScrollView,TouchableOpacity,StyleSheet,Alert}from'react-native';
import{applyToJob,getJob,getOrganizationById,openConversation,submitReport}from'../lib/api';
import{C,R}from'../lib/theme';

export default function JobDetailScreen({route,navigation}:any){
 const id=route.params?.jobId||route.params?.id;const[post,setPost]=useState<any>(null);const[org,setOrg]=useState<any>(null);const[busy,setBusy]=useState(false);const[msgBusy,setMsgBusy]=useState(false);const[reportBusy,setReportBusy]=useState(false);
 useEffect(()=>{if(!id)return;getJob(id).then(async(x:any)=>{setPost(x);const embedded=x?.job?.organization;if(embedded)setOrg(embedded);else if(x?.job?.organization_id){try{setOrg(await getOrganizationById(x.job.organization_id))}catch{}}}).catch(()=>Alert.alert('Could not load job','Check your connection and try again.'))},[id]);
 if(!post)return<View style={s.page}/>;
 const j=post.job||{};const requirements=j.requirements||post.tags||[];const workplace=String(j.workplace_type||(j.is_remote?'remote':'on_site')).replace('_',' ');const location=j.location||org?.location||post.country_code||'Location not listed';
 const apply=async()=>{if(busy)return;setBusy(true);try{await applyToJob(id,{source:'job_detail'});Alert.alert('Application sent','Your WORKIT profile and proof of work were submitted.')}catch(e:any){const m=String(e?.message||'');Alert.alert('Could not apply',m.includes('already applied')||m.includes('409')?'You already applied to this job.':'The job may be unavailable. Check your connection and try again.')}finally{setBusy(false)}};
 const message=async()=>{if(msgBusy)return;if(!post.author?.id){Alert.alert('Employer unavailable','This employer cannot receive messages right now.');return}setMsgBusy(true);try{const c=await openConversation(post.author.id);navigation.navigate('Chat',{conversationId:c.id,other:post.author})}catch{Alert.alert('Could not open chat','Check your connection and try again.')}finally{setMsgBusy(false)}};
 const sendReport=async(reason:string)=>{if(reportBusy)return;setReportBusy(true);try{await submitReport({target_type:'job',target_id:id,reason});Alert.alert('Report sent','Thank you. This job has been added to the WORKIT moderation queue.')}catch{Alert.alert('Could not send report','Check your connection and try again.')}finally{setReportBusy(false)}};
 const report=()=>Alert.alert('Report this job','Choose the reason that best describes the problem.',[{text:'Scam or fraud',onPress:()=>void sendReport('scam')},{text:'Misleading job',onPress:()=>void sendReport('misleading')},{text:'Illegal or unsafe',onPress:()=>void sendReport('illegal')},{text:'Other',onPress:()=>void sendReport('other')},{text:'Cancel',style:'cancel'}]);
 const openCompany=()=>{if(j.organization_id)navigation.navigate('CompanyPublic',{id:j.organization_id})};
 return<ScrollView style={s.page} contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
  <TouchableOpacity onPress={()=>navigation.goBack()}><Text style={s.back}>‹ Back</Text></TouchableOpacity>
  <Text style={s.kicker}>WORKIT JOB</Text><Text style={s.h1}>{post.title}</Text>
  {j.organization_id?<TouchableOpacity onPress={openCompany} style={s.companyCard}><View style={{flex:1}}><View style={s.companyLine}><Text style={s.company}>{org?.name||j.company_name||'WORKIT employer'}</Text>{org?.verified&&<Text style={s.verified}>✓</Text>}</View><Text style={s.companyMeta}>{org?.industry||'Employer'}{org?.location?` · ${org.location}`:''}</Text></View><Text style={s.companyArrow}>→</Text></TouchableOpacity>:<Text style={s.companyPlain}>{j.company_name||'WORKIT employer'}</Text>}
  <View style={s.factGrid}><Fact icon="⌖" value={location} label="Location"/><Fact icon="●" value={workplace} label="Workplace"/><Fact icon="◷" value={j.schedule||'Schedule not listed'} label="Schedule"/><Fact icon="＋" value={`${j.positions||1}`} label={(j.positions||1)===1?'Position':'Positions'}/></View>
  <View style={s.metaRow}><Text style={s.meta}>{String(j.job_type||'job').replace('_',' ')}</Text>{post.application_count!==undefined&&<Text style={s.meta}>{post.application_count} applicants</Text>}</View>
  {(j.salary_min||j.salary_max)&&<Text style={s.salary}>Salary · {j.salary_min||'—'}{j.salary_max?` – ${j.salary_max}`:''}</Text>}
  <Text style={s.section}>About the role</Text><Text style={s.body}>{post.description||'See the WORKIT job post for full context.'}</Text>
  <Text style={s.section}>Skills / requirements</Text><View style={s.skills}>{requirements.length?requirements.map((x:string)=><Text key={x} style={s.skill}>{x}</Text>):<Text style={s.body}>No specific requirements listed.</Text>}</View>
  <TouchableOpacity style={[s.primary,busy&&s.disabled]} onPress={()=>void apply()} disabled={busy}><Text style={s.primaryTxt}>{busy?'Applying…':'Apply with WORKIT profile'}</Text></TouchableOpacity>
  <TouchableOpacity style={[s.secondary,msgBusy&&s.disabled]} onPress={()=>void message()} disabled={msgBusy}><Text style={s.secondaryTxt}>{msgBusy?'Opening chat…':'Message employer'}</Text></TouchableOpacity>
  <TouchableOpacity style={[s.report,reportBusy&&s.disabled]} onPress={report} disabled={reportBusy}><Text style={s.reportTxt}>{reportBusy?'Sending report…':'Report this job'}</Text></TouchableOpacity>
 </ScrollView>
}
const Fact=({icon,value,label}:any)=><View style={s.fact}><Text style={s.factIcon}>{icon}</Text><Text numberOfLines={2} style={s.factValue}>{value}</Text><Text style={s.factLabel}>{label}</Text></View>;
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{padding:18,paddingTop:54,paddingBottom:90},back:{color:C.muted,fontSize:12,fontWeight:'800'},kicker:{color:C.violetSoft,fontSize:8,fontWeight:'900',letterSpacing:1.2,marginTop:28},h1:{color:C.text,fontSize:31,fontWeight:'900',lineHeight:36,marginTop:7},companyCard:{minHeight:72,borderRadius:16,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,marginTop:15,padding:12,flexDirection:'row',alignItems:'center'},companyLine:{flexDirection:'row',alignItems:'center',gap:5},company:{color:C.text,fontSize:13,fontWeight:'900'},verified:{color:C.blue2,fontSize:13,fontWeight:'900'},companyMeta:{color:C.muted,fontSize:8,marginTop:4},companyArrow:{color:C.text,fontSize:21},companyPlain:{color:C.violetSoft,fontSize:13,fontWeight:'900',marginTop:14},factGrid:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:14},fact:{width:'48.9%',minHeight:78,borderRadius:14,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,padding:10},factIcon:{color:C.violetSoft,fontSize:14},factValue:{color:C.text,fontSize:10,fontWeight:'900',marginTop:7,textTransform:'capitalize'},factLabel:{color:C.faint,fontSize:7,marginTop:3},metaRow:{flexDirection:'row',gap:7,marginTop:12},meta:{color:C.muted,fontSize:8,fontWeight:'800',borderWidth:1,borderColor:C.line,paddingHorizontal:9,paddingVertical:6,borderRadius:R.pill,textTransform:'capitalize'},salary:{color:C.text,fontSize:14,fontWeight:'900',marginTop:20},section:{color:C.text,fontSize:14,fontWeight:'900',marginTop:25,marginBottom:8},body:{color:C.muted,fontSize:12,lineHeight:19},skills:{flexDirection:'row',flexWrap:'wrap',gap:7},skill:{color:C.violetSoft,fontSize:8,fontWeight:'800',paddingHorizontal:9,paddingVertical:6,borderRadius:R.pill,backgroundColor:C.panel,borderWidth:1,borderColor:C.line},primary:{height:54,borderRadius:16,backgroundColor:C.text,alignItems:'center',justifyContent:'center',marginTop:28},primaryTxt:{color:C.black,fontSize:12,fontWeight:'900'},secondary:{height:50,borderRadius:16,borderWidth:1,borderColor:C.line,alignItems:'center',justifyContent:'center',marginTop:9},secondaryTxt:{color:C.text,fontSize:11,fontWeight:'900'},report:{height:44,alignItems:'center',justifyContent:'center',marginTop:10},reportTxt:{color:C.red,fontSize:9,fontWeight:'900'},disabled:{opacity:.55}});