import React from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { C } from '../lib/theme';

const copy:any={
 privacy:{title:'Privacy Policy',body:['WORKIT should collect only the data needed to operate professional profiles, hiring, messaging, marketplace transactions, safety and fraud prevention.','Before public launch, this screen must be replaced with a production privacy policy covering data categories, legal bases, retention, processors, user rights, international transfers and contact details.']},
 terms:{title:'Terms of Service',body:['WORKIT connects professionals, employers, buyers and sellers. Users remain responsible for the accuracy and legality of their listings, work claims, jobs, products and services.','Before public launch, this screen must be replaced with counsel-approved Terms covering eligibility, accounts, content licensing, hiring, marketplace transactions, disputes, suspension, liability and governing law.']},
 community:{title:'Community Guidelines',body:['WORKIT is for real work, real opportunities and professional proof. Fraud, scams, harassment, hate, sexual exploitation, violent threats, illegal goods, impersonation and deceptive employment or marketplace offers are prohibited.','Users can report content or accounts. Repeated or severe violations can result in content removal, account restrictions or permanent removal.']},
 marketplace:{title:'Marketplace & Payment Rules',body:['Listings must accurately describe the service, product or lesson being offered. Sellers must deliver what was purchased and buyers must use the dispute process when something goes wrong.','WORKIT may charge platform fees and may hold, reverse or refund transactions according to the final payments and dispute policy. Production payment terms must be finalized before launch.']},
 safety:{title:'Safety & Reporting',body:['Report suspicious job offers, payment requests outside approved flows, impersonation, harassment, illegal content or misleading professional claims.','For launch, WORKIT will route reports into a moderation queue. Emergency situations should be reported to the appropriate local authorities rather than relying on WORKIT support.']}
};

export default function LegalScreen({navigation,route}:any){const section=route?.params?.section||'community';const c=copy[section]||copy.community;return <ScrollView style={s.page} contentContainerStyle={s.content}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={s.back}>‹ Back</Text></TouchableOpacity><Text style={s.kicker}>WORKIT TRUST CENTER</Text><Text style={s.h1}>{c.title}</Text><View style={s.card}>{c.body.map((p:string,i:number)=><Text key={i} style={s.p}>{p}</Text>)}</View><View style={s.draft}><Text style={s.draftT}>PRE-LAUNCH POLICY DRAFT</Text><Text style={s.draftB}>Product structure is ready; final legal text must be approved for the countries where WORKIT launches.</Text></View></ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingTop:54,paddingHorizontal:18,paddingBottom:70},back:{color:C.blue2,fontSize:12,fontWeight:'800',marginBottom:20},kicker:{color:C.green,fontSize:9,fontWeight:'900',letterSpacing:1.2},h1:{color:C.text,fontSize:30,fontWeight:'900',letterSpacing:-1,marginTop:5,marginBottom:18},card:{borderRadius:20,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,padding:18},p:{color:C.text,fontSize:13,lineHeight:21,marginBottom:16},draft:{marginTop:14,borderRadius:16,borderWidth:1,borderColor:'#3A3121',backgroundColor:'#17130C',padding:14},draftT:{color:C.amber,fontSize:8,fontWeight:'900',letterSpacing:1},draftB:{color:C.muted,fontSize:10,lineHeight:16,marginTop:6}});
