import React,{useCallback,useEffect,useState}from'react';
import{Alert,ScrollView,StyleSheet,Text,TouchableOpacity,View}from'react-native';
import{useFocusEffect}from'@react-navigation/native';
import{getMyApplications,openConversation}from'../lib/api';
import{C,F,R,S}from'../lib/theme';
const stages=['new','reviewed','shortlisted','interview','offer','hired'];
const statusMessage=(x:string)=>({new:'Application sent. The employer can now review your profile.',reviewed:'Your application has been reviewed.',shortlisted:'You made the shortlist.',interview:'The employer wants to speak with you.',offer:'You received an offer. Open the conversation for details.',hired:'You’re hired. This role can now become verified WORKIT history.',rejected:'This application is no longer moving forward.'} as any)[x]||'Application updated.';
export default function MyApplicationsScreen({navigation}:any){
 const[items,setItems]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[openingChat,setOpeningChat]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const r=await getMyApplications();setItems(r.items||r||[])}catch{setItems([])}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);useFocusEffect(useCallback(()=>{void load();return()=>{}},[load]));
 const openRole=(a:any)=>{const id=a.job_post_id||a.job?.id;if(id)navigation.navigate('JobDetail',{jobId:id})};
 const chat=async(a:any)=>{const employer=a.job?.author;if(!employer?.id)return Alert.alert('Employer unavailable','This employer profile is not available right now.');if(openingChat)return;setOpeningChat(a.id);try{const c=await openConversation(employer.id);navigation.navigate('Chat',{conversationId:c.id,other:employer})}catch{Alert.alert('Could not open conversation','Check your connection and try again.')}finally{setOpeningChat(null)}};
 return<ScrollView style={s.page} contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
  <View style={s.head}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={s.back}>‹ Back</Text></TouchableOpacity><Text style={s.wordmark}>WORK<Text style={{color:C.violet2}}>IT</Text></Text></View>
  <Text style={s.kicker}>YOUR CAREER PIPELINE</Text><Text style={s.h1}>My Applications</Text><Text style={s.sub}>Follow every application from sent to hired. Your latest video pitch is attached automatically when available.</Text>
  {loading?<Text style={s.empty}>Loading applications…</Text>:items.length?items.map((a:any)=>{const post=a.job||{};const jd=post.job||{};const status=String(a.status||'new');const current=Math.max(0,stages.indexOf(status));const action=status==='interview'?'Open interview chat':status==='offer'?'View offer conversation':status==='hired'?'Message employer':'View role';const chatBusy=openingChat===a.id;return<View key={a.id} style={[s.card,status==='hired'&&s.hiredCard]}>
   <TouchableOpacity onPress={()=>openRole(a)} activeOpacity={.85}><View style={s.top}><View style={{flex:1}}><Text style={s.company}>{jd.company_name||'WORKIT employer'}</Text><Text style={s.title}>{post.title||'Job application'}</Text></View><View style={[s.status,{borderColor:stageColor(status)}]}><Text style={[s.statusTxt,{color:stageColor(status)}]}>{status.toUpperCase()}</Text></View></View>
   <Text style={s.meta}>{jd.location||post.country_code||(jd.is_remote?'Remote':'Location not listed')}{a.created_at?` · Applied ${new Date(a.created_at).toLocaleDateString()}`:''}</Text>
   <Text style={[s.statusBody,status==='hired'&&{color:C.green}]}>{statusMessage(status)}</Text>
   {a.video_cf_uid?<View style={s.pitch}><Text style={s.pitchIcon}>▶</Text><Text style={s.pitchTxt}>Video pitch included</Text></View>:<View style={s.pitchMissing}><Text style={s.pitchMissingTxt}>Profile-only application · no pitch attached</Text></View>}
   <View style={s.track}>{stages.map((x,i)=><View key={x} style={[s.dot,i<=current&&status!=='rejected'&&s.dotOn,status==='hired'&&i<=current&&s.dotHired]}/>)}</View></TouchableOpacity>
   <View style={s.actionRow}><TouchableOpacity onPress={()=>openRole(a)} style={s.secondary}><Text style={s.secondaryTxt}>Role</Text></TouchableOpacity><TouchableOpacity disabled={chatBusy} onPress={()=>['interview','offer','hired'].includes(status)?void chat(a):openRole(a)} style={[s.primary,chatBusy&&{opacity:.55},status==='hired'&&s.hiredPrimary]}><Text style={[s.primaryTxt,status==='hired'&&s.hiredPrimaryTxt]}>{chatBusy?'Opening…':action}</Text></TouchableOpacity></View>
  </View>}):<View style={s.emptyCard}><Text style={s.emptyT}>No applications yet.</Text><Text style={s.empty}>Find a role in Explore and apply with your WORKIT profile. Your latest pitch is included when you have one.</Text><TouchableOpacity onPress={()=>navigation.navigate('MainTabs',{screen:'Explore'})} style={s.btn}><Text style={s.btnTxt}>Find jobs</Text></TouchableOpacity></View>}
 </ScrollView>}
const stageColor=(x:string)=>x==='hired'?C.green:x==='rejected'?C.red:x==='offer'?C.gold:x==='interview'?C.blue2:C.violetSoft;
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingTop:S.top,paddingHorizontal:S.pageX,paddingBottom:90},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},back:{color:C.violetSoft,fontSize:12,fontWeight:'800'},wordmark:{color:C.text,fontFamily:F.display,fontSize:27,fontWeight:'700'},kicker:{color:C.violetSoft,fontSize:9,fontWeight:'900',letterSpacing:1.4,marginTop:24},h1:{color:C.text,fontSize:31,fontWeight:'900',letterSpacing:-1,marginTop:5},sub:{color:C.muted,fontSize:12,lineHeight:18,marginTop:5,marginBottom:18},card:{borderWidth:1,borderColor:C.lineSoft,borderRadius:R.lg,backgroundColor:C.panel,padding:15,marginBottom:10},hiredCard:{borderColor:'rgba(71,226,154,.34)',backgroundColor:'rgba(71,226,154,.04)'},top:{flexDirection:'row',alignItems:'flex-start',gap:10},company:{color:C.violetSoft,fontSize:9,fontWeight:'900'},title:{color:C.text,fontSize:16,fontWeight:'900',marginTop:3},status:{borderWidth:1,borderRadius:R.pill,paddingHorizontal:8,paddingVertical:5},statusTxt:{fontSize:7,fontWeight:'900'},meta:{color:C.muted,fontSize:9,marginTop:7},statusBody:{color:C.text,fontSize:9.5,lineHeight:15,marginTop:10,fontWeight:'700'},pitch:{alignSelf:'flex-start',borderRadius:R.pill,backgroundColor:'rgba(139,92,246,.10)',borderWidth:1,borderColor:'rgba(139,92,246,.30)',paddingHorizontal:9,paddingVertical:6,marginTop:11,flexDirection:'row',gap:6,alignItems:'center'},pitchIcon:{color:C.violetSoft,fontSize:8},pitchTxt:{color:C.text,fontSize:8,fontWeight:'900'},pitchMissing:{alignSelf:'flex-start',marginTop:11},pitchMissingTxt:{color:C.faint,fontSize:8},track:{flexDirection:'row',gap:5,marginTop:14},dot:{flex:1,height:4,borderRadius:2,backgroundColor:C.panel3},dotOn:{backgroundColor:C.violet},dotHired:{backgroundColor:C.green},actionRow:{flexDirection:'row',gap:8,marginTop:14},secondary:{height:42,paddingHorizontal:16,borderRadius:12,borderWidth:1,borderColor:C.line,alignItems:'center',justifyContent:'center'},secondaryTxt:{color:C.text,fontSize:9,fontWeight:'900'},primary:{flex:1,height:42,borderRadius:12,backgroundColor:C.text,alignItems:'center',justifyContent:'center'},primaryTxt:{color:C.black,fontSize:9,fontWeight:'900'},hiredPrimary:{backgroundColor:C.green},hiredPrimaryTxt:{color:C.black},emptyCard:{borderWidth:1,borderColor:C.lineSoft,borderRadius:R.lg,backgroundColor:C.panel,padding:18,marginTop:10},emptyT:{color:C.text,fontSize:16,fontWeight:'900'},empty:{color:C.muted,fontSize:11,lineHeight:17,marginTop:8},btn:{alignSelf:'flex-start',backgroundColor:C.violet,borderRadius:12,paddingHorizontal:14,paddingVertical:10,marginTop:14},btnTxt:{color:'#fff',fontSize:9,fontWeight:'900'}});