import React,{useCallback,useMemo,useState}from'react';
import{ScrollView,StyleSheet,Text,TouchableOpacity,View}from'react-native';
import{useFocusEffect}from'@react-navigation/native';
import{getMyOrders}from'../lib/api';
import{C,F,R,S}from'../lib/theme';
export default function MyOrdersScreen({navigation,route}:any){
 const[items,setItems]=useState<any[]>([]);const[loading,setLoading]=useState(true);const focusId=route.params?.focusOrderId;
 const load=useCallback(async()=>{setLoading(true);try{const r=await getMyOrders();setItems(r.items||r||[])}catch{setItems([])}finally{setLoading(false)}},[]);
 useFocusEffect(useCallback(()=>{void load();return()=>{}},[load]));
 const ordered=useMemo(()=>focusId?[...items].sort((a,b)=>a.id===focusId?-1:b.id===focusId?1:0):items,[items,focusId]);
 return<ScrollView style={s.page} contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
  <View style={s.head}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={s.back}>‹ Back</Text></TouchableOpacity><Text style={s.wordmark}>WORK<Text style={{color:C.violet2}}>IT</Text></Text></View><Text style={s.kicker}>WORK IN PROGRESS</Text><Text style={s.h1}>My Orders</Text><Text style={s.sub}>Bookings, products, lessons and services — in one delivery workspace.</Text>
  {loading?<Text style={s.empty}>Loading orders…</Text>:ordered.length?ordered.map((o:any)=>{const focused=o.id===focusId;return<TouchableOpacity key={o.id} onPress={()=>o.market_item_id&&navigation.navigate('MarketDetail',{id:o.market_item_id})} style={[s.card,focused&&s.focused]}><View style={s.top}><View style={{flex:1}}><Text style={s.type}>{focused?'OPENED FROM CHAT · ':''}{String(o.market_type||o.market_item?.type||o.type||'order').toUpperCase()}</Text><Text style={s.title}>{o.title||o.market_item?.title||'WORKIT order'}</Text></View><Text style={[s.status,{color:statusColor(o.status)}]}>{String(o.status||'pending').replace('_',' ').toUpperCase()}</Text></View><Text style={s.meta}>{o.seller_name||o.buyer_name||o.other_party?.full_name||o.market_item?.seller?.full_name||'WORKIT professional'}</Text><View style={s.money}><Text style={s.amount}>{o.currency||'EUR'} {Number(o.gross_amount??o.amount??o.market_item?.price_amount??0).toFixed(0)}</Text><Text style={s.open}>Open listing →</Text></View></TouchableOpacity>}):<View style={s.emptyCard}><Text style={s.emptyT}>No orders yet.</Text><Text style={s.empty}>Book a service, buy a product or learn from an expert in WORKIT Market.</Text><TouchableOpacity onPress={()=>navigation.navigate('MainTabs',{screen:'Market'})} style={s.btn}><Text style={s.btnTxt}>Open Market</Text></TouchableOpacity></View>}
 </ScrollView>}
const statusColor=(x:string)=>['completed','delivered'].includes(x)?C.green:['cancelled','disputed'].includes(x)?C.red:C.gold;
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingTop:S.top,paddingHorizontal:S.pageX,paddingBottom:90},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},back:{color:C.violetSoft,fontSize:12,fontWeight:'800'},wordmark:{color:C.text,fontFamily:F.display,fontSize:27,fontWeight:'700'},kicker:{color:C.violetSoft,fontSize:9,fontWeight:'900',letterSpacing:1.4,marginTop:24},h1:{color:C.text,fontSize:31,fontWeight:'900',letterSpacing:-1,marginTop:5},sub:{color:C.muted,fontSize:12,lineHeight:18,marginTop:5,marginBottom:18},card:{borderWidth:1,borderColor:C.lineSoft,borderRadius:R.lg,backgroundColor:C.panel,padding:15,marginBottom:10},focused:{borderColor:C.violetSoft,backgroundColor:'rgba(139,92,246,.08)'},top:{flexDirection:'row',alignItems:'flex-start',gap:10},type:{color:C.violetSoft,fontSize:8,fontWeight:'900',letterSpacing:1},title:{color:C.text,fontSize:16,fontWeight:'900',marginTop:4},status:{fontSize:7,fontWeight:'900'},meta:{color:C.muted,fontSize:9,marginTop:7},money:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:14,paddingTop:12,borderTopWidth:1,borderColor:C.lineSoft},amount:{color:C.text,fontSize:15,fontWeight:'900'},open:{color:C.violetSoft,fontSize:9,fontWeight:'900'},emptyCard:{borderWidth:1,borderColor:C.lineSoft,borderRadius:R.lg,backgroundColor:C.panel,padding:18,marginTop:10},emptyT:{color:C.text,fontSize:16,fontWeight:'900'},empty:{color:C.muted,fontSize:11,lineHeight:17,marginTop:8},btn:{alignSelf:'flex-start',backgroundColor:C.violet,borderRadius:12,paddingHorizontal:14,paddingVertical:10,marginTop:14},btnTxt:{color:'#fff',fontSize:9,fontWeight:'900'}});