import React, { useEffect, useState } from 'react';
import { View, Text, TouchableOpacity, StyleSheet, ScrollView } from 'react-native';
import { getNotifications, markAllNotificationsRead } from '../lib/api';
import { C, F, R, S } from '../lib/theme';

export default function NotificationsScreen({navigation}:any){
 const [items,setItems]=useState<any[]>([]); const [loading,setLoading]=useState(true);
 const load=()=>{setLoading(true);getNotifications().then(r=>setItems(r.items||r||[])).catch(()=>setItems([])).finally(()=>setLoading(false))};
 useEffect(()=>{load()},[]);
 const readAll=async()=>{try{await markAllNotificationsRead();setItems(p=>p.map(x=>({...x,read_at:x.read_at||new Date().toISOString()})))}catch{}};
 return <ScrollView style={s.page} contentContainerStyle={s.content}>
   <View style={s.head}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={s.back}>‹</Text></TouchableOpacity><View style={{flex:1}}><Text style={s.title}>Notifications</Text><Text style={s.sub}>Hiring, orders, messages and work updates.</Text></View><TouchableOpacity onPress={readAll} style={s.readBtn}><Text style={s.readTxt}>Read all</Text></TouchableOpacity></View>
   {loading?<Text style={s.empty}>Loading notifications…</Text>:items.length?items.map((n:any,i:number)=><TouchableOpacity key={n.id||i} style={[s.card,!n.read_at&&s.unread]} onPress={()=>navigateFromNotification(n,navigation)}><View style={[s.dot,!n.read_at&&s.dotOn]}/><View style={{flex:1}}><Text style={s.cardTitle}>{n.title||labelFor(n.type)}</Text><Text style={s.cardBody}>{n.body||n.message||'WORKIT update'}</Text><Text style={s.time}>{formatTime(n.created_at)}</Text></View><Text style={s.arrow}>›</Text></TouchableOpacity>):<View style={s.emptyCard}><Text style={s.emptyTitle}>You're all caught up.</Text><Text style={s.empty}>New hiring, marketplace and account activity will appear here.</Text></View>}
 </ScrollView>
}
function labelFor(type:string){return ({message:'New message',application:'Application update',order:'Order update',follow:'New follower',review:'New review'} as any)[type]||'WORKIT update'}
function formatTime(v?:string){if(!v)return '';const d=new Date(v);const diff=Math.max(0,Date.now()-d.getTime());const m=Math.floor(diff/60000);if(m<60)return `${Math.max(1,m)} min ago`;const h=Math.floor(m/60);if(h<24)return `${h} hr ago`;return `${Math.floor(h/24)} d ago`}
function navigateFromNotification(n:any,navigation:any){if(n.conversation_id)return navigation.navigate('Chat',{conversationId:n.conversation_id});if(n.job_post_id)return navigation.navigate('JobDetail',{jobId:n.job_post_id});if(n.market_item_id)return navigation.navigate('MarketDetail',{id:n.market_item_id});if(n.profile_username)return navigation.navigate('Professional',{username:n.profile_username});}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingTop:S.top,paddingHorizontal:S.pageX,paddingBottom:80},head:{flexDirection:'row',alignItems:'flex-start',gap:11},back:{color:C.text,fontSize:36,lineHeight:38},title:{color:C.text,fontFamily:F.display,fontSize:29},sub:{color:C.muted,fontSize:10,marginTop:3},readBtn:{height:34,paddingHorizontal:11,borderRadius:R.pill,borderWidth:1,borderColor:C.line,alignItems:'center',justifyContent:'center'},readTxt:{color:C.violetSoft,fontSize:8,fontWeight:'900'},card:{minHeight:82,marginTop:9,borderRadius:16,borderWidth:1,borderColor:C.lineSoft,backgroundColor:C.panel,padding:13,flexDirection:'row',alignItems:'center',gap:10},unread:{borderColor:'#4C3A83',backgroundColor:'#111326'},dot:{width:7,height:7,borderRadius:4,backgroundColor:C.faint},dotOn:{backgroundColor:C.violet2},cardTitle:{color:C.text,fontSize:12,fontWeight:'900'},cardBody:{color:C.muted,fontSize:10,lineHeight:15,marginTop:4},time:{color:C.faint,fontSize:8,marginTop:6},arrow:{color:C.text,fontSize:23},emptyCard:{marginTop:30,minHeight:160,borderRadius:18,borderWidth:1,borderColor:C.lineSoft,backgroundColor:C.panel,alignItems:'center',justifyContent:'center',padding:20},emptyTitle:{color:C.text,fontFamily:F.display,fontSize:22},empty:{color:C.muted,fontSize:10,lineHeight:16,textAlign:'center',marginTop:7}});
