import React,{useCallback,useEffect,useState}from'react';
import{View,Text,TouchableOpacity,StyleSheet,ScrollView}from'react-native';
import{useFocusEffect}from'@react-navigation/native';
import{getNotifications,markAllNotificationsRead}from'../lib/api';
import{C,F,R,S}from'../lib/theme';

export default function NotificationsScreen({navigation}:any){
 const[items,setItems]=useState<any[]>([]);const[loading,setLoading]=useState(true);
 const load=useCallback(()=>{setLoading(true);getNotifications().then(r=>setItems(r.items||r||[])).catch(()=>setItems([])).finally(()=>setLoading(false))},[]);
 useEffect(()=>{load()},[load]);useFocusEffect(useCallback(()=>{load();return()=>{}},[load]));
 const readAll=async()=>{try{await markAllNotificationsRead();setItems(p=>p.map(x=>({...x,is_read:true})))}catch{}};
 return<ScrollView style={s.page} contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
  <View style={s.head}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={s.back}>‹</Text></TouchableOpacity><View style={{flex:1}}><Text style={s.title}>Notifications</Text><Text style={s.sub}>Hiring, messages and work updates.</Text></View><TouchableOpacity onPress={readAll} style={s.readBtn}><Text style={s.readTxt}>Read all</Text></TouchableOpacity></View>
  {loading?<Text style={s.empty}>Loading notifications…</Text>:items.length?items.map((n:any,i:number)=>{const unread=!n.is_read;return<TouchableOpacity key={n.id||i} style={[s.card,unread&&s.unread]} onPress={()=>navigateFromNotification(n,navigation)}><View style={[s.dot,unread&&s.dotOn]}/><View style={{flex:1}}><Text style={s.cardTitle}>{labelFor(n)}</Text><Text style={s.cardBody}>{n.body||'WORKIT update'}</Text><Text style={s.time}>{formatTime(n.created_at)}</Text></View><Text style={s.arrow}>›</Text></TouchableOpacity>}):<View style={s.emptyCard}><Text style={s.emptyTitle}>You're all caught up.</Text><Text style={s.empty}>New hiring, marketplace and account activity will appear here.</Text></View>}
 </ScrollView>
}
function labelFor(n:any){const body=String(n.body||'').toLowerCase();if(n.type==='application'){if(body.includes('interview'))return'Interview invite';if(body.includes('offer'))return'Offer received';if(body.includes('hired'))return'You’re hired';if(body.includes('shortlisted'))return'Shortlisted';return'Application update'}return({message:'New message',order:'Order update',follow:'New follower',hire_request:'Hiring update',system:'WORKIT update'} as any)[n.type]||'WORKIT update'}
function formatTime(v?:string){if(!v)return'';const d=new Date(v);const diff=Math.max(0,Date.now()-d.getTime());const m=Math.floor(diff/60000);if(m<60)return`${Math.max(1,m)} min ago`;const h=Math.floor(m/60);if(h<24)return`${h} hr ago`;return`${Math.floor(h/24)} d ago`}
function navigateFromNotification(n:any,navigation:any){if(n.type==='message'){if(n.conversation_id)navigation.navigate('Chat',{conversationId:n.conversation_id});else navigation.navigate('Inbox');return}if(n.type==='application'&&n.post_id){navigation.navigate('JobDetail',{jobId:n.post_id});return}if(n.post_id){navigation.navigate('JobDetail',{jobId:n.post_id});return}if(n.actor?.username){navigation.navigate('Professional',{username:n.actor.username,profile:n.actor});return}}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingTop:S.top,paddingHorizontal:S.pageX,paddingBottom:80},head:{flexDirection:'row',alignItems:'flex-start',gap:11},back:{color:C.text,fontSize:36,lineHeight:38},title:{color:C.text,fontFamily:F.display,fontSize:29},sub:{color:C.muted,fontSize:10,marginTop:3},readBtn:{height:34,paddingHorizontal:11,borderRadius:R.pill,borderWidth:1,borderColor:C.line,alignItems:'center',justifyContent:'center'},readTxt:{color:C.violetSoft,fontSize:8,fontWeight:'900'},card:{minHeight:82,marginTop:9,borderRadius:16,borderWidth:1,borderColor:C.lineSoft,backgroundColor:C.panel,padding:13,flexDirection:'row',alignItems:'center',gap:10},unread:{borderColor:'#4C3A83',backgroundColor:'#111326'},dot:{width:7,height:7,borderRadius:4,backgroundColor:C.faint},dotOn:{backgroundColor:C.violet2},cardTitle:{color:C.text,fontSize:12,fontWeight:'900'},cardBody:{color:C.muted,fontSize:10,lineHeight:15,marginTop:4},time:{color:C.faint,fontSize:8,marginTop:6},arrow:{color:C.text,fontSize:23},emptyCard:{marginTop:30,minHeight:160,borderRadius:18,borderWidth:1,borderColor:C.lineSoft,backgroundColor:C.panel,alignItems:'center',justifyContent:'center',padding:20},emptyTitle:{color:C.text,fontFamily:F.display,fontSize:22},empty:{color:C.muted,fontSize:10,lineHeight:16,textAlign:'center',marginTop:7}});