import React,{useMemo,useState}from'react';
import{Alert,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View}from'react-native';
import{updateMe}from'../lib/api';
import{C,F,R,S}from'../lib/theme';
import{getProfessionProfile}from'../lib/professionProfile';

const split=(v:string)=>v.split(',').map(x=>x.trim()).filter(Boolean);
const professions=['Electrician','Welder','Architect','Nurse','Chef','Barber','Dancer','Teacher','Designer','Developer','Driver'];
export default function OnboardingScreen({onDone}:any){
 const[step,setStep]=useState(0);const[busy,setBusy]=useState(false);const[fullName,setFullName]=useState('');const[title,setTitle]=useState('');const[location,setLocation]=useState('');const[skills,setSkills]=useState('');const[tools,setTools]=useState('');const[bio,setBio]=useState('');
 const cfg=useMemo(()=>getProfessionProfile(title),[title]);
 const canNext=useMemo(()=>step===0?!!fullName.trim()&&!!title.trim():step===1?!!skills.trim():true,[step,fullName,title,skills]);
 const finish=async()=>{setBusy(true);try{await updateMe({full_name:fullName.trim(),title:title.trim(),location:location.trim(),skills:split(skills),tools:split(tools),bio:bio.trim(),available_for_work:true,onboarding_completed:true});onDone?.()}catch{Alert.alert('Could not finish setup','Please try again.')}finally{setBusy(false)}};
 return<ScrollView style={s.page} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
  <Text style={s.wordmark}>WORK<Text style={{color:C.violet2}}>IT</Text></Text><Text style={s.tag}>VIDEO-FIRST HIRING</Text>
  <View style={s.progress}>{[0,1,2].map(i=><View key={i} style={[s.bar,i<=step&&s.barOn]}/>)}</View>
  {step===0&&<><Text style={s.kicker}>01 · WHO ARE YOU?</Text><Text style={s.h1}>What do you do?</Text><Text style={s.sub}>Pick your profession. WORKIT adapts your profile around the proof employers need to see.</Text><Input label="Full name" value={fullName} onChange={setFullName} placeholder="Your name"/><Text style={s.label}>Profession</Text><View style={s.profGrid}>{professions.map(p=><TouchableOpacity key={p} onPress={()=>setTitle(p)} style={[s.prof,title===p&&s.profOn]}><Text style={[s.profTxt,title===p&&s.profTxtOn]}>{p}</Text></TouchableOpacity>)}</View><Input label="Or type another profession" value={title} onChange={setTitle} placeholder="e.g. Carpenter, Dentist, Performer"/><Input label="Location" value={location} onChange={setLocation} placeholder="City, Country"/></>}
  {step===1&&<><Text style={s.kicker}>02 · PROOF</Text><Text style={s.h1}>{cfg.proofLabel} first.</Text><Text style={s.sub}>{cfg.pitchHint}</Text><View style={s.context}><Text style={s.contextK}>{cfg.label.toUpperCase()}</Text><Text style={s.contextT}>Your profile will prioritize {cfg.primarySections.slice(0,3).join(', ')}.</Text></View><Input label="Skills" value={skills} onChange={setSkills} placeholder={cfg.highlightTerms.length?cfg.highlightTerms.join(', '):'Your strongest skills'}/><Input label="Tools / software / equipment" value={tools} onChange={setTools} placeholder="Add what you actually use at work"/></>}
  {step===2&&<><Text style={s.kicker}>03 · YOUR PITCH</Text><Text style={s.h1}>Why should someone hire you?</Text><Text style={s.sub}>Keep it human and concrete. Your video will do most of the talking; this text just gives context.</Text><Input label="Short professional intro" value={bio} onChange={setBio} placeholder={`I’m a ${title||'professional'} based in ${location||'your city'}...`} area/><View style={s.promise}><Text style={s.promiseK}>NEXT</Text><Text style={s.promiseT}>Post a short video pitch.</Text><Text style={s.promiseB}>Show your face, show your work, say what you’re available for.</Text></View></>}
  <View style={s.actions}>{step>0&&<TouchableOpacity onPress={()=>setStep(x=>x-1)} style={s.back}><Text style={s.backTxt}>‹</Text></TouchableOpacity>}<TouchableOpacity disabled={!canNext||busy} onPress={()=>step<2?setStep(x=>x+1):finish()} style={[s.next,{opacity:!canNext||busy?.5:1}]}><Text style={s.nextTxt}>{step<2?'Continue':'Enter WORKIT'}</Text><Text style={s.nextTxt}>→</Text></TouchableOpacity></View>
 </ScrollView>}
const Input=({label,value,onChange,placeholder,area}:any)=><View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChange} placeholder={placeholder} placeholderTextColor={C.faint} multiline={!!area} style={[s.input,area&&s.area]}/></View>;
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingTop:S.top+12,paddingHorizontal:24,paddingBottom:80},wordmark:{color:C.text,fontFamily:F.body,fontSize:38,fontWeight:'900',letterSpacing:-1.8},tag:{color:C.muted,fontSize:7,fontWeight:'800',letterSpacing:2.1,marginTop:-2},progress:{flexDirection:'row',gap:6,marginTop:38},bar:{flex:1,height:3,borderRadius:2,backgroundColor:C.line},barOn:{backgroundColor:C.violet},kicker:{color:C.violetSoft,fontSize:9,fontWeight:'900',letterSpacing:1.4,marginTop:30},h1:{color:C.text,fontSize:35,fontWeight:'900',lineHeight:39,letterSpacing:-1.4,marginTop:8},sub:{color:C.muted,fontSize:13,lineHeight:20,marginTop:10},field:{marginTop:19},label:{color:C.text,fontSize:10,fontWeight:'900',marginTop:18,marginBottom:7},input:{borderWidth:1,borderColor:C.lineSoft,borderRadius:16,backgroundColor:C.panel,paddingHorizontal:14,paddingVertical:14,color:C.text,fontSize:13},area:{minHeight:118,textAlignVertical:'top'},profGrid:{flexDirection:'row',flexWrap:'wrap',gap:8},prof:{paddingHorizontal:12,paddingVertical:10,borderRadius:R.pill,borderWidth:1,borderColor:C.line,backgroundColor:C.panel},profOn:{backgroundColor:C.violet,borderColor:C.violetSoft},profTxt:{color:C.muted,fontSize:10,fontWeight:'800'},profTxtOn:{color:'#fff'},context:{marginTop:18,borderRadius:16,borderWidth:1,borderColor:'#30275C',backgroundColor:'#141126',padding:14},contextK:{color:C.violetSoft,fontSize:8,fontWeight:'900',letterSpacing:1.1},contextT:{color:C.text,fontSize:11,fontWeight:'800',marginTop:5},promise:{marginTop:20,borderRadius:R.lg,borderWidth:1,borderColor:'#32285F',backgroundColor:'#141126',padding:17},promiseK:{color:C.violetSoft,fontSize:8,fontWeight:'900',letterSpacing:1.1},promiseT:{color:C.text,fontSize:16,fontWeight:'900',marginTop:7},promiseB:{color:C.muted,fontSize:10,marginTop:5},actions:{flexDirection:'row',gap:9,marginTop:26},back:{width:54,height:54,borderRadius:16,borderWidth:1,borderColor:C.line,alignItems:'center',justifyContent:'center'},backTxt:{color:C.text,fontSize:25,fontWeight:'800'},next:{flex:1,height:54,borderRadius:16,backgroundColor:C.violet,paddingHorizontal:17,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},nextTxt:{color:'#fff',fontSize:12,fontWeight:'900'}});