import React,{useMemo,useState}from'react';
import{Alert,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View}from'react-native';
import{updateMe}from'../lib/api';
import{C,F,R,S}from'../lib/theme';

const split=(v:string)=>v.split(',').map(x=>x.trim()).filter(Boolean);
export default function OnboardingScreen({onDone}:any){
 const[step,setStep]=useState(0);const[busy,setBusy]=useState(false);const[fullName,setFullName]=useState('');const[title,setTitle]=useState('');const[location,setLocation]=useState('');const[skills,setSkills]=useState('');const[tools,setTools]=useState('');const[bio,setBio]=useState('');
 const canNext=useMemo(()=>step===0?!!fullName.trim()&&!!title.trim():step===1?!!skills.trim():true,[step,fullName,title,skills]);
 const finish=async()=>{setBusy(true);try{await updateMe({full_name:fullName.trim(),title:title.trim(),location:location.trim(),skills:split(skills),tools:split(tools),bio:bio.trim(),available_for_work:true,onboarding_completed:true});onDone?.()}catch{Alert.alert('Could not finish setup','Please try again.')}finally{setBusy(false)}};
 return<ScrollView style={s.page} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
  <Text style={s.wordmark}>WORK<Text style={{color:C.violet2}}>IT</Text></Text><Text style={s.tag}>THE WORLD'S BIGGEST WORK BAZAAR</Text>
  <View style={s.progress}>{[0,1,2].map(i=><View key={i} style={[s.bar,i<=step&&s.barOn]}/>)}</View>
  {step===0&&<><Text style={s.kicker}>STEP 1 · PROFESSIONAL IDENTITY</Text><Text style={s.h1}>What should the world know you for?</Text><Text style={s.sub}>Your profession drives discovery, job matching and the actions WORKIT shows around your profile.</Text><Input label="Full name" value={fullName} onChange={setFullName} placeholder="Your name"/><Input label="Profession / title" value={title} onChange={setTitle} placeholder="Architect, Barber, Nurse, Developer..."/><Input label="Location" value={location} onChange={setLocation} placeholder="City, Country"/></>}
  {step===1&&<><Text style={s.kicker}>STEP 2 · PROOF SIGNALS</Text><Text style={s.h1}>Show what you can actually do.</Text><Text style={s.sub}>Skills and software become searchable employer signals — not decorative profile text.</Text><Input label="Skills" value={skills} onChange={setSkills} placeholder="3D Visualization, Welding, React, Hair Colouring"/><Input label="Tools & software" value={tools} onChange={setTools} placeholder="AutoCAD, Revit, Figma, Excel"/></>}
  {step===2&&<><Text style={s.kicker}>STEP 3 · YOUR WORK STORY</Text><Text style={s.h1}>Give people a reason to contact you.</Text><Text style={s.sub}>Keep it concrete: what you do, who you help and what kind of work you want next.</Text><Input label="Professional bio" value={bio} onChange={setBio} placeholder="I design sustainable residential spaces and 3D visualizations for clients worldwide." area/><View style={s.promise}><Text style={s.promiseK}>WORKIT PROMISE</Text><Text style={s.promiseT}>Free to join. Free to show your work.</Text><Text style={s.promiseB}>WORKIT earns when WORKIT creates economic value.</Text></View></>}
  <View style={s.actions}>{step>0&&<TouchableOpacity onPress={()=>setStep(x=>x-1)} style={s.back}><Text style={s.backTxt}>Back</Text></TouchableOpacity>}<TouchableOpacity disabled={!canNext||busy} onPress={()=>step<2?setStep(x=>x+1):finish()} style={[s.next,{opacity:!canNext||busy?.5:1}]}><Text style={s.nextTxt}>{step<2?'Continue':'Enter WORKIT'}</Text><Text style={s.nextTxt}>→</Text></TouchableOpacity></View>
 </ScrollView>}
const Input=({label,value,onChange,placeholder,area}:any)=><View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChange} placeholder={placeholder} placeholderTextColor={C.faint} multiline={!!area} style={[s.input,area&&s.area]}/></View>;
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingTop:S.top+12,paddingHorizontal:24,paddingBottom:80},wordmark:{color:C.text,fontFamily:F.display,fontSize:38,fontWeight:'700',letterSpacing:-1.8},tag:{color:C.muted,fontSize:7,fontWeight:'800',letterSpacing:2.1,marginTop:-2},progress:{flexDirection:'row',gap:6,marginTop:38},bar:{flex:1,height:3,borderRadius:2,backgroundColor:C.line},barOn:{backgroundColor:C.violet},kicker:{color:C.violetSoft,fontSize:9,fontWeight:'900',letterSpacing:1.4,marginTop:30},h1:{color:C.text,fontSize:35,fontWeight:'900',lineHeight:39,letterSpacing:-1.4,marginTop:8},sub:{color:C.muted,fontSize:13,lineHeight:20,marginTop:10},field:{marginTop:19},label:{color:C.text,fontSize:10,fontWeight:'900',marginBottom:7},input:{borderWidth:1,borderColor:C.lineSoft,borderRadius:16,backgroundColor:C.panel,paddingHorizontal:14,paddingVertical:14,color:C.text,fontSize:13},area:{minHeight:118,textAlignVertical:'top'},promise:{marginTop:20,borderRadius:R.lg,borderWidth:1,borderColor:'#32285F',backgroundColor:'#141126',padding:17},promiseK:{color:C.violetSoft,fontSize:8,fontWeight:'900',letterSpacing:1.1},promiseT:{color:C.text,fontSize:16,fontWeight:'900',marginTop:7},promiseB:{color:C.muted,fontSize:10,marginTop:5},actions:{flexDirection:'row',gap:9,marginTop:26},back:{height:54,paddingHorizontal:20,borderRadius:16,borderWidth:1,borderColor:C.line,alignItems:'center',justifyContent:'center'},backTxt:{color:C.text,fontSize:11,fontWeight:'800'},next:{flex:1,height:54,borderRadius:16,backgroundColor:C.violet,paddingHorizontal:17,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},nextTxt:{color:'#fff',fontSize:12,fontWeight:'900'}});