import React,{useEffect,useState}from'react';
import{Alert,ScrollView,StyleSheet,Switch,Text,TouchableOpacity,View}from'react-native';
import{getPreferences,updateMe}from'../lib/api';
import{C,F,R,S}from'../lib/theme';

export default function PreferencesScreen({navigation}:any){
 const[prefs,setPrefs]=useState<any>({messages:true,applications:true,orders:true,marketing:false});const[busy,setBusy]=useState(false);
 useEffect(()=>{getPreferences().then((r:any)=>setPrefs({...prefs,...(r.notification_preferences||{})})).catch(()=>{})},[]);
 const set=(k:string,v:boolean)=>setPrefs((p:any)=>({...p,[k]:v}));
 const save=async()=>{setBusy(true);try{await updateMe({notification_preferences:prefs});Alert.alert('Saved','Notification preferences updated.')}catch{Alert.alert('Could not save','Please try again.')}finally{setBusy(false)}};
 return<ScrollView style={s.page} contentContainerStyle={s.content}><View style={s.head}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={s.back}>‹ Settings</Text></TouchableOpacity><Text style={s.wordmark}>WORK<Text style={{color:C.violet2}}>IT</Text></Text></View><Text style={s.kicker}>NOTIFICATIONS</Text><Text style={s.h1}>Only the signals that matter.</Text><Text style={s.sub}>Control what WORKIT should notify you about.</Text><View style={s.card}><Row t="Messages" b="New client, employer and professional messages" value={prefs.messages} on={(v:boolean)=>set('messages',v)}/><Row t="Applications & hiring" b="Application updates, shortlists, interviews and offers" value={prefs.applications} on={(v:boolean)=>set('applications',v)}/><Row t="Orders & bookings" b="New orders, deliveries, bookings and disputes" value={prefs.orders} on={(v:boolean)=>set('orders',v)}/><Row t="WORKIT updates" b="Product news, growth tips and occasional marketing" value={prefs.marketing} on={(v:boolean)=>set('marketing',v)} last/></View><TouchableOpacity disabled={busy} onPress={save} style={s.save}><Text style={s.saveTxt}>{busy?'Saving…':'Save preferences'}</Text><Text style={s.saveTxt}>→</Text></TouchableOpacity></ScrollView>}
const Row=({t,b,value,on,last}:any)=><View style={[s.row,last&&{borderBottomWidth:0}]}><View style={{flex:1}}><Text style={s.rowT}>{t}</Text><Text style={s.rowB}>{b}</Text></View><Switch value={!!value} onValueChange={on} trackColor={{true:C.violet}}/></View>;
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingTop:S.top,paddingHorizontal:S.pageX,paddingBottom:80},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},back:{color:C.violetSoft,fontSize:12,fontWeight:'800'},wordmark:{color:C.text,fontFamily:F.display,fontSize:27,fontWeight:'700'},kicker:{color:C.violetSoft,fontSize:9,fontWeight:'900',letterSpacing:1.3,marginTop:26},h1:{color:C.text,fontSize:30,fontWeight:'900',letterSpacing:-1,marginTop:6},sub:{color:C.muted,fontSize:12,marginTop:6},card:{marginTop:20,borderRadius:R.lg,borderWidth:1,borderColor:C.lineSoft,backgroundColor:C.panel,overflow:'hidden'},row:{minHeight:78,paddingHorizontal:15,paddingVertical:14,borderBottomWidth:1,borderBottomColor:C.lineSoft,flexDirection:'row',alignItems:'center',gap:10},rowT:{color:C.text,fontSize:13,fontWeight:'900'},rowB:{color:C.muted,fontSize:9,lineHeight:14,marginTop:4,maxWidth:250},save:{height:54,borderRadius:16,backgroundColor:C.violet,marginTop:18,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},saveTxt:{color:'#fff',fontSize:11,fontWeight:'900'}});