import React,{useCallback,useState}from'react';
import{Alert,Image,ScrollView,StyleSheet,Text,TouchableOpacity,View}from'react-native';
import{useFocusEffect}from'@react-navigation/native';
import{getSavedMarket,unsaveMarketItem}from'../lib/api';
import{C,F,R,S}from'../lib/theme';
export default function SavedItemsScreen({navigation}:any){
 const[items,setItems]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[removing,setRemoving]=useState<Record<string,boolean>>({});
 const load=useCallback(async()=>{setLoading(true);try{const r=await getSavedMarket();setItems(r.items||r||[])}catch{setItems([])}finally{setLoading(false)}},[]);
 useFocusEffect(useCallback(()=>{void load();return()=>{}},[load]));
 const remove=async(id:string)=>{if(removing[id])return;setRemoving(p=>({...p,[id]:true}));try{await unsaveMarketItem(id);setItems(x=>x.filter((i:any)=>i.id!==id))}catch{Alert.alert('Could not remove item','Check your connection and try again.')}finally{setRemoving(p=>({...p,[id]:false}))}};
 return<ScrollView style={s.page} contentContainerStyle={s.content}><View style={s.head}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={s.back}>‹ Back</Text></TouchableOpacity><Text style={s.wordmark}>WORK<Text style={{color:C.violet2}}>IT</Text></Text></View><Text style={s.kicker}>YOUR SHORTLIST</Text><Text style={s.h1}>Saved</Text><Text style={s.sub}>Services, products and lessons you want to come back to.</Text>{loading?<Text style={s.empty}>Loading saved items…</Text>:items.length?items.map((i:any)=><View key={i.id} style={s.card}>{i.media_url||i.thumbnail_url?<Image source={{uri:i.media_url||i.thumbnail_url}} style={s.img}/>:<View style={[s.img,s.ph]}><Text style={s.phTxt}>W</Text></View>}<View style={s.body}><Text style={s.type}>{String(i.type||'listing').toUpperCase()}</Text><Text numberOfLines={2} style={s.title}>{i.title}</Text><Text style={s.meta}>{i.seller?.full_name||i.seller_name||'WORKIT professional'}</Text><View style={s.actions}><TouchableOpacity onPress={()=>navigation.navigate('MarketDetail',{id:i.id})} style={s.open}><Text style={s.openTxt}>View</Text></TouchableOpacity><TouchableOpacity disabled={!!removing[i.id]} onPress={()=>void remove(i.id)} style={[s.remove,removing[i.id]&&s.disabled]}><Text style={s.removeTxt}>{removing[i.id]?'Removing…':'Remove'}</Text></TouchableOpacity></View></View></View>):<View style={s.emptyCard}><Text style={s.emptyT}>Nothing saved yet.</Text><Text style={s.empty}>Tap the heart on a Market listing to build your shortlist.</Text><TouchableOpacity onPress={()=>navigation.navigate('MainTabs',{screen:'Market'})} style={s.btn}><Text style={s.btnTxt}>Browse Market</Text></TouchableOpacity></View>}</ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingTop:S.top,paddingHorizontal:S.pageX,paddingBottom:90},head:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{color:C.violetSoft,fontSize:12,fontWeight:'800'},wordmark:{color:C.text,fontFamily:F.display,fontSize:27,fontWeight:'700'},kicker:{color:C.violetSoft,fontSize:9,fontWeight:'900',letterSpacing:1.3,marginTop:24},h1:{color:C.text,fontSize:31,fontWeight:'900',letterSpacing:-1,marginTop:5},sub:{color:C.muted,fontSize:12,marginTop:5,marginBottom:18},card:{borderWidth:1,borderColor:C.lineSoft,borderRadius:R.lg,backgroundColor:C.panel,overflow:'hidden',flexDirection:'row',marginBottom:10,minHeight:132},img:{width:118,height:'100%'},ph:{backgroundColor:C.panel2,alignItems:'center',justifyContent:'center'},phTxt:{color:C.violetSoft,fontFamily:F.display,fontSize:32},body:{flex:1,padding:13},type:{color:C.violetSoft,fontSize:8,fontWeight:'900',letterSpacing:.8},title:{color:C.text,fontSize:15,fontWeight:'900',lineHeight:19,marginTop:5},meta:{color:C.muted,fontSize:9,marginTop:5},actions:{flexDirection:'row',gap:7,marginTop:11},open:{backgroundColor:C.violet,borderRadius:10,paddingHorizontal:13,paddingVertical:8},openTxt:{color:'#fff',fontSize:8,fontWeight:'900'},remove:{borderWidth:1,borderColor:C.line,borderRadius:10,paddingHorizontal:12,paddingVertical:8},removeTxt:{color:C.muted,fontSize:8,fontWeight:'800'},disabled:{opacity:.5},emptyCard:{borderWidth:1,borderColor:C.lineSoft,borderRadius:R.lg,backgroundColor:C.panel,padding:18},emptyT:{color:C.text,fontSize:16,fontWeight:'900'},empty:{color:C.muted,fontSize:11,lineHeight:17,marginTop:8},btn:{alignSelf:'flex-start',backgroundColor:C.violet,borderRadius:12,paddingHorizontal:14,paddingVertical:10,marginTop:14},btnTxt:{color:'#fff',fontSize:9,fontWeight:'900'}});