import React,{useCallback,useState}from'react';
import{Alert,Image,ScrollView,StyleSheet,Text,TouchableOpacity,View}from'react-native';
import{useFocusEffect}from'@react-navigation/native';
import{getSavedCandidates,unsaveCandidate}from'../lib/talentPool';
import{C,F,R,S}from'../lib/theme';

export default function SavedCandidatesScreen({navigation}:any){
 const[items,setItems]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[busyId,setBusyId]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{const r=await getSavedCandidates();setItems(r.items||[])}catch{setItems([]);Alert.alert('Could not load talent pool','Check your connection and try again.')}finally{setLoading(false)}},[]);
 useFocusEffect(useCallback(()=>{void load();return()=>{}},[load]));
 const remove=async(id:string)=>{if(busyId)return;setBusyId(id);try{await unsaveCandidate(id);setItems(p=>p.filter(x=>x.id!==id))}catch{Alert.alert('Could not remove candidate','Please try again.')}finally{setBusyId('')}};
 const open=(p:any)=>p.username&&navigation.navigate('Professional',{username:p.username,profile:p});
 const invite=(p:any)=>navigation.navigate('CandidateInvite',{candidate:p});
 return<ScrollView style={s.page} contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
  <View style={s.top}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={s.back}>‹</Text></TouchableOpacity><View style={{flex:1}}><Text style={s.wordmark}>WORK<Text style={s.it}>IT</Text></Text><Text style={s.tagline}>PRIVATE TALENT POOL</Text></View></View>
  <Text style={s.h1}>People worth remembering.</Text><Text style={s.sub}>Save strong candidates before you are ready to invite them. Your talent pool is private to you.</Text>
  {loading?<Text style={s.empty}>Loading saved candidates…</Text>:items.length?<View style={s.stack}>{items.map((p:any)=><View key={p.id} style={s.card}>
   <TouchableOpacity onPress={()=>open(p)} style={s.person} activeOpacity={.86}>{p.avatar_url?<Image source={{uri:p.avatar_url}} style={s.avatar}/>:<View style={[s.avatar,s.ph]}><Text style={s.initial}>{p.full_name?.[0]||'W'}</Text></View>}<View style={{flex:1}}><View style={s.nameRow}><Text numberOfLines={1} style={s.name}>{p.full_name||'WORKIT professional'} {p.verified?'✓':''}</Text><Text style={s.rating}>★ {Number(p.rating||0)?Number(p.rating).toFixed(1):'—'}</Text></View><Text style={s.role}>{p.title||'Professional'}</Text><Text style={s.meta}>⌖ {p.location||'Location'} · {p.completed_jobs||0} jobs</Text><View style={s.tags}>{[...(p.skills||[]),...(p.tools||[])].slice(0,3).map((x:string)=><Text key={x} style={s.tag}>{x}</Text>)}</View></View></TouchableOpacity>
   {!!p.saved_note&&<Text style={s.note}>{p.saved_note}</Text>}
   <View style={s.actions}><TouchableOpacity onPress={()=>invite(p)} style={s.primary}><Text style={s.primaryTxt}>Invite to job</Text></TouchableOpacity><TouchableOpacity onPress={()=>open(p)} style={s.secondary}><Text style={s.secondaryTxt}>Profile</Text></TouchableOpacity><TouchableOpacity disabled={busyId===p.id} onPress={()=>void remove(p.id)} style={s.remove}><Text style={s.removeTxt}>{busyId===p.id?'…':'×'}</Text></TouchableOpacity></View>
  </View>)}</View>:<View style={s.emptyCard}><Text style={s.emptyTitle}>Your talent pool is empty.</Text><Text style={s.empty}>Save people from Explore so you can return to them later.</Text><TouchableOpacity onPress={()=>navigation.navigate('MainTabs',{screen:'Explore'})} style={s.explore}><Text style={s.exploreTxt}>Find people</Text></TouchableOpacity></View>}
 </ScrollView>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingTop:S.top,paddingHorizontal:S.pageX,paddingBottom:100},top:{flexDirection:'row',alignItems:'center',gap:12},back:{color:C.text,fontSize:34},wordmark:{color:C.text,fontFamily:F.body,fontSize:27,fontWeight:'900',letterSpacing:-1.2},it:{color:C.violet2},tagline:{color:C.faint,fontSize:7,fontWeight:'900',letterSpacing:1.8,marginTop:-1},h1:{color:C.text,fontSize:31,fontWeight:'900',lineHeight:35,letterSpacing:-1.1,marginTop:24},sub:{color:C.muted,fontSize:11.5,lineHeight:18,marginTop:7,marginBottom:18},stack:{gap:9},card:{borderWidth:1,borderColor:C.lineSoft,borderRadius:18,backgroundColor:C.panel,padding:11},person:{flexDirection:'row',gap:10},avatar:{width:68,height:78,borderRadius:14},ph:{backgroundColor:C.panel2,alignItems:'center',justifyContent:'center'},initial:{color:C.text,fontSize:24,fontWeight:'900'},nameRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},name:{color:C.text,fontSize:12.5,fontWeight:'900',maxWidth:'78%'},rating:{color:C.gold,fontSize:8,fontWeight:'900'},role:{color:C.violetSoft,fontSize:10,fontWeight:'800',marginTop:3},meta:{color:C.muted,fontSize:8,marginTop:5},tags:{flexDirection:'row',flexWrap:'wrap',gap:5,marginTop:7},tag:{color:C.muted,fontSize:7,fontWeight:'800',paddingHorizontal:7,paddingVertical:4,borderRadius:R.pill,borderWidth:1,borderColor:C.line},note:{color:C.muted,fontSize:9,lineHeight:14,marginTop:10,paddingTop:9,borderTopWidth:1,borderColor:C.lineSoft},actions:{flexDirection:'row',gap:7,marginTop:11},primary:{flex:1,height:42,borderRadius:12,backgroundColor:C.violet,alignItems:'center',justifyContent:'center'},primaryTxt:{color:'#fff',fontSize:9,fontWeight:'900'},secondary:{height:42,paddingHorizontal:13,borderRadius:12,borderWidth:1,borderColor:C.line,alignItems:'center',justifyContent:'center'},secondaryTxt:{color:C.text,fontSize:9,fontWeight:'900'},remove:{width:42,height:42,borderRadius:12,borderWidth:1,borderColor:C.line,alignItems:'center',justifyContent:'center'},removeTxt:{color:C.muted,fontSize:20,fontWeight:'500'},emptyCard:{borderWidth:1,borderStyle:'dashed',borderColor:C.line,borderRadius:18,padding:22,alignItems:'center',marginTop:8},emptyTitle:{color:C.text,fontSize:15,fontWeight:'900'},empty:{color:C.muted,fontSize:10,lineHeight:16,textAlign:'center',marginTop:7},explore:{marginTop:14,height:42,paddingHorizontal:16,borderRadius:12,backgroundColor:C.violet,alignItems:'center',justifyContent:'center'},exploreTxt:{color:'#fff',fontSize:9,fontWeight:'900'}});