import React,{useState}from'react';
import{Alert,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View}from'react-native';
import{openConversation,sendMessage}from'../lib/api';
import{scheduleInterview}from'../lib/hiringInvites';
import{C,F,R,S}from'../lib/theme';

const modes=[['video','Video call'],['in_person','In person'],['phone','Phone']] as const;
const durations=[20,30,45,60];
const parseLocal=(v:string)=>{const clean=v.trim().replace(' ','T');const d=new Date(clean.length===16?`${clean}:00`:clean);return Number.isNaN(d.getTime())?null:d};
const fmt=(iso:string)=>new Date(iso).toLocaleString([], {weekday:'short',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
export default function ScheduleInterviewScreen({route,navigation}:any){
 const application=route.params?.application||{};const job=route.params?.job||{};const candidate=route.params?.candidate||application.applicant||{};const jd=job.job||application.job?.job||{};
 const[mode,setMode]=useState<'video'|'in_person'|'phone'>('video');const[duration,setDuration]=useState(30);const[location,setLocation]=useState(jd.location||'');const[slots,setSlots]=useState(['','','']);const[busy,setBusy]=useState(false);
 const title=job.title||application.job?.title||'WORKIT role';
 const parsed=slots.map(parseLocal).filter(Boolean) as Date[];const canSend=parsed.length>0&&!busy&&(mode!=='in_person'||!!location.trim());
 const setSlot=(i:number,v:string)=>setSlots(p=>p.map((x,n)=>n===i?v:x));
 const submit=async()=>{if(!canSend)return;setBusy(true);try{const iso=parsed.map(d=>d.toISOString());await scheduleInterview(application.id,{slots:iso,mode,location:location.trim()||null,duration_minutes:duration});let conversation:any=null;try{conversation=await openConversation(candidate.id);const lines=[`[WORKIT_JOB:${job.id||application.job_post_id}] Interview · ${title}`,'',`${mode==='video'?'Video interview':mode==='phone'?'Phone interview':'In-person interview'} · ${duration} min`,location.trim()?`Location / link · ${location.trim()}`:'','',...iso.map((x,i)=>`${i+1}. ${fmt(x)}`),'','Choose your preferred slot in My Applications.'].filter(Boolean);await sendMessage(conversation.id,lines.join('\n'))}catch{Alert.alert('Interview scheduled','The candidate was notified in WORKIT, but the chat message could not be delivered.')}if(conversation?.id)navigation.replace('Chat',{conversationId:conversation.id,other:candidate});else navigation.goBack()}catch(e:any){Alert.alert('Could not schedule interview',e?.message||'Check the interview details and try again.')}finally{setBusy(false)}};
 return<ScrollView style={s.page} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
  <View style={s.top}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={s.back}>‹</Text></TouchableOpacity><Text style={s.wordmark}>WORK<Text style={s.it}>IT</Text></Text><View style={{width:30}}/></View>
  <Text style={s.kicker}>INTERVIEW</Text><Text style={s.h1}>Pick times. Not email chains.</Text><Text style={s.sub}>Give {candidate?.full_name||'the candidate'} a few clear options for <Text style={s.strong}>{title}</Text>. They choose one inside WORKIT.</Text>
  <Text style={s.label}>INTERVIEW TYPE</Text><View style={s.chips}>{modes.map(([k,label])=><TouchableOpacity key={k} onPress={()=>setMode(k)} style={[s.chip,mode===k&&s.chipOn]}><Text style={[s.chipTxt,mode===k&&s.chipTxtOn]}>{label}</Text></TouchableOpacity>)}</View>
  <Text style={s.label}>DURATION</Text><View style={s.chips}>{durations.map(x=><TouchableOpacity key={x} onPress={()=>setDuration(x)} style={[s.chip,duration===x&&s.chipOn]}><Text style={[s.chipTxt,duration===x&&s.chipTxtOn]}>{x} min</Text></TouchableOpacity>)}</View>
  {(mode==='in_person'||mode==='video')&&<View style={s.field}><Text style={s.fieldLabel}>{mode==='video'?'MEETING LINK / LOCATION':'LOCATION'}</Text><TextInput value={location} onChangeText={setLocation} placeholder={mode==='video'?'Add link now or agree it in chat':'e.g. Valletta office'} placeholderTextColor={C.faint} style={s.input}/></View>}
  <Text style={s.label}>OFFER UP TO 3 TIMES</Text><View style={s.slotCard}>{slots.map((v,i)=><View key={i} style={s.slotRow}><View style={s.slotNo}><Text style={s.slotNoTxt}>{i+1}</Text></View><TextInput value={v} onChangeText={x=>setSlot(i,x)} placeholder="YYYY-MM-DD HH:MM" placeholderTextColor={C.faint} style={s.slotInput}/></View>)}<Text style={s.hint}>Times are interpreted in the employer’s local device timezone and shown locally to the candidate.</Text></View>
  {!!parsed.length&&<View style={s.preview}><Text style={s.previewK}>CANDIDATE WILL SEE</Text>{parsed.map((d,i)=><Text key={i} style={s.previewT}>{i+1}. {fmt(d.toISOString())}</Text>)}</View>}
  <TouchableOpacity disabled={!canSend} onPress={()=>void submit()} style={[s.send,!canSend&&s.disabled]}><View><Text style={s.sendK}>SEND INTERVIEW OPTIONS</Text><Text style={s.sendT}>{busy?'Scheduling…':'Let them choose'}</Text></View><Text style={s.arrow}>→</Text></TouchableOpacity>
 </ScrollView>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingTop:S.top,paddingHorizontal:S.pageX,paddingBottom:100},top:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{color:C.text,fontSize:35},wordmark:{color:C.text,fontFamily:F.body,fontSize:26,fontWeight:'900',letterSpacing:-1.2},it:{color:C.violet2},kicker:{color:C.blue2,fontSize:8,fontWeight:'900',letterSpacing:1.4,marginTop:25},h1:{color:C.text,fontSize:31,fontWeight:'900',letterSpacing:-1,marginTop:6},sub:{color:C.muted,fontSize:12,lineHeight:19,marginTop:8},strong:{color:C.text,fontWeight:'900'},label:{color:C.faint,fontSize:8,fontWeight:'900',letterSpacing:1,marginTop:20,marginBottom:8},chips:{flexDirection:'row',gap:7,flexWrap:'wrap'},chip:{height:36,paddingHorizontal:12,borderRadius:R.pill,borderWidth:1,borderColor:C.line,alignItems:'center',justifyContent:'center',backgroundColor:C.panel},chipOn:{backgroundColor:C.text,borderColor:C.text},chipTxt:{color:C.muted,fontSize:8.5,fontWeight:'900'},chipTxtOn:{color:C.black},field:{marginTop:18},fieldLabel:{color:C.faint,fontSize:8,fontWeight:'900',letterSpacing:.8,marginBottom:7},input:{height:46,borderWidth:1,borderColor:C.line,borderRadius:13,backgroundColor:C.panel,color:C.text,paddingHorizontal:12,fontSize:11},slotCard:{borderWidth:1,borderColor:C.lineSoft,borderRadius:18,backgroundColor:C.panel,padding:11},slotRow:{flexDirection:'row',alignItems:'center',gap:8,marginBottom:8},slotNo:{width:30,height:42,borderRadius:11,backgroundColor:C.panel2,alignItems:'center',justifyContent:'center'},slotNoTxt:{color:C.blue2,fontSize:10,fontWeight:'900'},slotInput:{flex:1,height:42,borderWidth:1,borderColor:C.line,borderRadius:11,color:C.text,paddingHorizontal:11,fontSize:11,backgroundColor:C.panel2},hint:{color:C.faint,fontSize:7.5,lineHeight:12,marginTop:2},preview:{marginTop:12,borderRadius:14,borderWidth:1,borderColor:'rgba(91,161,255,.25)',backgroundColor:'rgba(91,161,255,.05)',padding:11},previewK:{color:C.blue2,fontSize:7,fontWeight:'900',letterSpacing:.9,marginBottom:5},previewT:{color:C.text,fontSize:9,fontWeight:'800',marginTop:4},send:{height:60,borderRadius:16,backgroundColor:C.text,marginTop:18,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},disabled:{opacity:.4},sendK:{color:C.faint,fontSize:7,fontWeight:'900',letterSpacing:.7},sendT:{color:C.black,fontSize:11,fontWeight:'900',marginTop:2},arrow:{color:C.black,fontSize:23}});