import React,{useState}from'react';
import{Alert,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View}from'react-native';
import{openConversation,sendMessage}from'../lib/api';
import{sendStructuredOffer}from'../lib/hiringInvites';
import{C,F,S}from'../lib/theme';

export default function SendOfferScreen({route,navigation}:any){
 const application=route.params?.application||{};const job=route.params?.job||{};const candidate=route.params?.candidate||application.applicant||{};const jd=job.job||application.job?.job||{};
 const[compensation,setCompensation]=useState('');const[startDate,setStartDate]=useState('');const[contract,setContract]=useState(String(jd.job_type||'').replaceAll('_',' '));const[schedule,setSchedule]=useState(jd.schedule||'');const[location,setLocation]=useState(jd.location||'');const[note,setNote]=useState('');const[busy,setBusy]=useState(false);
 const title=job.title||application.job?.title||'WORKIT role';const canSend=!!compensation.trim()&&!busy;
 const submit=async()=>{if(!canSend)return;setBusy(true);try{const updated=await sendStructuredOffer(application.id,{compensation:compensation.trim(),start_date:startDate.trim()||null,contract:contract.trim()||null,schedule:schedule.trim()||null,location:location.trim()||null,note:note.trim()||null});let conversation:any=null;try{conversation=await openConversation(candidate.id);const lines=[`[WORKIT_JOB:${job.id||application.job_post_id}] Offer · ${title}`,'',`Compensation · ${compensation.trim()}`,startDate.trim()?`Start date · ${startDate.trim()}`:'',contract.trim()?`Contract · ${contract.trim()}`:'',schedule.trim()?`Schedule · ${schedule.trim()}`:'',location.trim()?`Location · ${location.trim()}`:'',note.trim()?`Note · ${note.trim()}`:'','',`Review the terms in My Applications, then accept or decline the offer.`].filter(Boolean);await sendMessage(conversation.id,lines.join('\n'))}catch{Alert.alert('Offer sent','The structured offer was saved and the candidate was notified, but the chat message could not be delivered.')}if(conversation?.id)navigation.replace('Chat',{conversationId:conversation.id,other:candidate});else navigation.goBack();return updated}catch(e:any){Alert.alert('Could not send offer',e?.message||'Please check the terms and try again.')}finally{setBusy(false)}};
 return<ScrollView style={s.page} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
  <View style={s.top}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={s.back}>‹</Text></TouchableOpacity><Text style={s.wordmark}>WORK<Text style={s.it}>IT</Text></Text><View style={{width:30}}/></View>
  <Text style={s.kicker}>STRUCTURED OFFER</Text><Text style={s.h1}>Make the offer clear.</Text><Text style={s.sub}>Before {candidate?.full_name||'the candidate'} can accept, WORKIT records the terms they are accepting for <Text style={s.strong}>{title}</Text>.</Text>
  <View style={s.card}><Input label="Compensation" value={compensation} onChange={setCompensation} placeholder="e.g. €18/hour, €36,000/year, Negotiable"/><Input label="Start date" value={startDate} onChange={setStartDate} placeholder="YYYY-MM-DD"/><Input label="Contract / employment type" value={contract} onChange={setContract} placeholder="Full time, part time, seasonal..."/><Input label="Schedule" value={schedule} onChange={setSchedule} placeholder="Mon–Fri · 07:00–16:00"/><Input label="Location" value={location} onChange={setLocation} placeholder="Valletta, Malta / Remote"/><Input label="Offer note" value={note} onChange={setNote} placeholder="Any final detail the candidate should know before accepting." area/></View>
  <View style={s.trust}><Text style={s.trustK}>WHAT HAPPENS NEXT</Text><Text style={s.trustT}>The candidate sees these terms in My Applications and chooses Accept or Decline. WORKIT only enables “Hired” after an explicit acceptance.</Text></View>
  <TouchableOpacity disabled={!canSend} onPress={()=>void submit()} style={[s.send,!canSend&&s.disabled]}><View><Text style={s.sendK}>SEND TO {String(candidate?.full_name||'CANDIDATE').toUpperCase()}</Text><Text style={s.sendT}>{busy?'Sending structured offer…':'Send offer'}</Text></View><Text style={s.arrow}>→</Text></TouchableOpacity>
 </ScrollView>
}
const Input=({label,value,onChange,placeholder,area}:any)=><View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChange} placeholder={placeholder} placeholderTextColor={C.faint} multiline={!!area} style={[s.input,area&&s.area]}/></View>;
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingTop:S.top,paddingHorizontal:S.pageX,paddingBottom:100},top:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{color:C.text,fontSize:35},wordmark:{color:C.text,fontFamily:F.body,fontSize:26,fontWeight:'900',letterSpacing:-1.2},it:{color:C.violet2},kicker:{color:C.gold,fontSize:8,fontWeight:'900',letterSpacing:1.4,marginTop:25},h1:{color:C.text,fontSize:32,fontWeight:'900',letterSpacing:-1.1,marginTop:6},sub:{color:C.muted,fontSize:12,lineHeight:19,marginTop:8},strong:{color:C.text,fontWeight:'900'},card:{borderWidth:1,borderColor:C.lineSoft,borderRadius:19,backgroundColor:C.panel,padding:13,marginTop:19},field:{marginBottom:13},label:{color:C.text,fontSize:9,fontWeight:'900',marginBottom:6},input:{borderWidth:1,borderColor:C.line,borderRadius:13,backgroundColor:C.panel2,color:C.text,fontSize:11,paddingHorizontal:12,paddingVertical:12},area:{minHeight:96,textAlignVertical:'top'},trust:{marginTop:12,borderRadius:15,borderWidth:1,borderColor:'rgba(245,183,66,.28)',backgroundColor:'rgba(245,183,66,.05)',padding:13},trustK:{color:C.gold,fontSize:7,fontWeight:'900',letterSpacing:1},trustT:{color:C.muted,fontSize:9.5,lineHeight:15,marginTop:5},send:{height:60,borderRadius:16,backgroundColor:C.text,marginTop:16,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},disabled:{opacity:.45},sendK:{color:C.faint,fontSize:7,fontWeight:'900',letterSpacing:.7},sendT:{color:C.black,fontSize:11,fontWeight:'900',marginTop:2},arrow:{color:C.black,fontSize:23}});