import React, { useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, StyleSheet, ActivityIndicator, ScrollView } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { getUploadUrl, api } from '../lib/api';
import { C, R, postMeta } from '../lib/theme';

const types=['video','hire_me','service','product','job','pitch','teach','donate'];

export default function UploadScreen(){
 const [title,setTitle]=useState(''); const [desc,setDesc]=useState(''); const [type,setType]=useState('video'); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState('');
 const pickAndUpload=async()=>{setMsg('');const pick=await ImagePicker.launchImageLibraryAsync({mediaTypes:ImagePicker.MediaTypeOptions.Videos,videoMaxDuration:180});if(pick.canceled)return;setBusy(true);try{const {uploadUrl,videoUid}=await getUploadUrl();const file=pick.assets[0];const form=new FormData();form.append('file',{uri:file.uri,name:'video.mp4',type:'video/mp4'} as any);await fetch(uploadUrl,{method:'POST',body:form});await api('/posts',{method:'POST',body:JSON.stringify({type,title,description:desc,cf_video_uid:videoUid})});setMsg('Published to the WORKIT bazaar.');setTitle('');setDesc('')}catch(e:any){setMsg('Upload failed: '+e.message)}setBusy(false)};
 const meta=postMeta[type];
 return <ScrollView style={s.page} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
   <Text style={s.kicker}>CREATE A WORK ACTION</Text><Text style={s.h1}>What are you putting into the world?</Text><Text style={s.sub}>Every WORKIT post should lead somewhere: show, hire, sell, teach, pitch or support.</Text>
   <View style={s.types}>{types.map(t=>{const m=postMeta[t];return <TouchableOpacity key={t} onPress={()=>setType(t)} style={[s.type,type===t&&{borderColor:m.accent,backgroundColor:'#141414'}]}><View style={[s.dot,{backgroundColor:m.accent}]}/><Text style={[s.typeTxt,type===t&&{color:C.text}]}>{m.label}</Text></TouchableOpacity>})}</View>
   <View style={s.preview}><Text style={[s.previewType,{color:meta.accent}]}>{meta.label}</Text><Text style={s.previewTitle}>{title||'Your work headline'}</Text><Text style={s.previewBody}>{desc||'Tell people what you do, what you are offering, and why they should care.'}</Text><View style={[s.previewCta,{backgroundColor:meta.accent}]}><Text style={s.previewCtaTxt}>{meta.cta} →</Text></View></View>
   <Text style={s.label}>Headline</Text><TextInput style={s.input} placeholder="e.g. I build custom oak kitchens in Pristina" placeholderTextColor={C.faint} value={title} onChangeText={setTitle}/>
   <Text style={s.label}>Context</Text><TextInput style={[s.input,s.area]} placeholder="What is happening in this video? Add proof, price, availability or outcome." placeholderTextColor={C.faint} multiline value={desc} onChangeText={setDesc}/>
   <TouchableOpacity style={[s.publish,{backgroundColor:meta.accent,opacity:busy||!title?.trim()?.6:1}]} onPress={pickAndUpload} disabled={busy||!title.trim()}>{busy?<ActivityIndicator color="#050505"/>:<><Text style={s.publishTxt}>Choose video & publish</Text><Text style={s.publishArrow}>↗</Text></>}</TouchableOpacity>
   {!!msg&&<Text style={s.msg}>{msg}</Text>}
 </ScrollView>
}

const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingTop:58,paddingHorizontal:18,paddingBottom:120},kicker:{color:C.blue2,fontSize:10,fontWeight:'900',letterSpacing:1.4},h1:{color:C.text,fontSize:29,fontWeight:'800',lineHeight:35,letterSpacing:-1,marginTop:6},sub:{color:C.muted,fontSize:13,lineHeight:20,marginTop:7},types:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:20},type:{flexDirection:'row',alignItems:'center',gap:7,paddingHorizontal:11,paddingVertical:8,borderRadius:R.pill,borderWidth:1,borderColor:C.line,backgroundColor:C.panel},dot:{width:6,height:6,borderRadius:3},typeTxt:{color:C.muted,fontSize:9,fontWeight:'900',letterSpacing:.5},preview:{marginTop:18,padding:18,borderRadius:22,backgroundColor:C.panel,borderWidth:1,borderColor:C.line},previewType:{fontSize:9,fontWeight:'900',letterSpacing:.9},previewTitle:{color:C.text,fontSize:17,fontWeight:'800',marginTop:8},previewBody:{color:C.muted,fontSize:12,lineHeight:18,marginTop:5},previewCta:{alignSelf:'flex-start',paddingHorizontal:12,paddingVertical:8,borderRadius:R.pill,marginTop:12},previewCtaTxt:{color:'#050505',fontSize:10,fontWeight:'900'},label:{color:C.text,fontSize:11,fontWeight:'800',marginTop:18,marginBottom:7},input:{backgroundColor:C.panel,borderWidth:1,borderColor:C.line,borderRadius:15,paddingHorizontal:14,paddingVertical:14,color:C.text,fontSize:14},area:{height:108,textAlignVertical:'top'},publish:{height:54,borderRadius:16,marginTop:20,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},publishTxt:{color:'#050505',fontSize:14,fontWeight:'900'},publishArrow:{color:'#050505',fontSize:19,fontWeight:'800'},msg:{color:C.green,textAlign:'center',fontSize:12,fontWeight:'700',marginTop:12}});
